import type { CountryAccess, Destination, ProfileSlide } from './types';

// Mobility scores approximate the Henley Passport Index (0–100 normalized).
// visaFree + restricted + impossible ≈ 195 destinations.
function mkCountry(name: string, code: string, score: number, visaFree: number): CountryAccess {
  const total = 195;
  const remaining = total - visaFree;
  const restricted = Math.round(remaining * 0.7);
  const impossible = remaining - restricted;
  return { name, code, visaFree, restricted, impossible, score };
}

const COUNTRY_LIST: CountryAccess[] = [
  mkCountry('Singapore', 'SG', 99, 195),
  mkCountry('Japan', 'JP', 98, 193),
  mkCountry('South Korea', 'KR', 97, 192),
  mkCountry('Germany', 'DE', 97, 191),
  mkCountry('Finland', 'FI', 97, 191),
  mkCountry('Italy', 'IT', 97, 191),
  mkCountry('Spain', 'ES', 97, 191),
  mkCountry('France', 'FR', 96, 190),
  mkCountry('Netherlands', 'NL', 96, 190),
  mkCountry('Sweden', 'SE', 96, 190),
  mkCountry('Norway', 'NO', 96, 189),
  mkCountry('Denmark', 'DK', 96, 189),
  mkCountry('Belgium', 'BE', 96, 189),
  mkCountry('Switzerland', 'CH', 96, 189),
  mkCountry('Ireland', 'IE', 96, 189),
  mkCountry('Austria', 'AT', 96, 189),
  mkCountry('Luxembourg', 'LU', 96, 189),
  mkCountry('Portugal', 'PT', 96, 189),
  mkCountry('Greece', 'GR', 95, 188),
  mkCountry('Czech Republic', 'CZ', 95, 188),
  mkCountry('New Zealand', 'NZ', 95, 188),
  mkCountry('United Kingdom', 'GB', 95, 188),
  mkCountry('Australia', 'AU', 95, 188),
  mkCountry('Malta', 'MT', 95, 188),
  mkCountry('Poland', 'PL', 95, 187),
  mkCountry('Hungary', 'HU', 95, 187),
  mkCountry('Canada', 'CA', 95, 187),
  mkCountry('United States', 'US', 96, 186),
  mkCountry('Estonia', 'EE', 95, 187),
  mkCountry('Lithuania', 'LT', 95, 187),
  mkCountry('Latvia', 'LV', 94, 186),
  mkCountry('Slovakia', 'SK', 94, 186),
  mkCountry('Slovenia', 'SI', 94, 186),
  mkCountry('Iceland', 'IS', 94, 186),
  mkCountry('Liechtenstein', 'LI', 92, 182),
  mkCountry('Cyprus', 'CY', 92, 182),
  mkCountry('Croatia', 'HR', 92, 182),
  mkCountry('Romania', 'RO', 91, 180),
  mkCountry('Bulgaria', 'BG', 91, 179),
  mkCountry('Monaco', 'MC', 91, 179),
  mkCountry('San Marino', 'SM', 90, 178),
  mkCountry('Andorra', 'AD', 86, 170),
  mkCountry('Chile', 'CL', 88, 174),
  mkCountry('UAE', 'AE', 92, 182),
  mkCountry('Argentina', 'AR', 86, 171),
  mkCountry('Brazil', 'BR', 88, 173),
  mkCountry('Mexico', 'MX', 80, 159),
  mkCountry('Israel', 'IL', 87, 172),
  mkCountry('Hong Kong', 'HK', 87, 171),
  mkCountry('Taiwan', 'TW', 75, 145),
  mkCountry('Macao', 'MO', 73, 144),
  mkCountry('Mauritius', 'MU', 75, 148),
  mkCountry('Seychelles', 'SC', 76, 152),
  mkCountry('Malaysia', 'MY', 90, 178),
  mkCountry('Uruguay', 'UY', 78, 154),
  mkCountry('Costa Rica', 'CR', 78, 153),
  mkCountry('Trinidad and Tobago', 'TT', 75, 148),
  mkCountry('Panama', 'PA', 75, 147),
  mkCountry('Ukraine', 'UA', 74, 146),
  mkCountry('Serbia', 'RS', 70, 137),
  mkCountry('North Macedonia', 'MK', 65, 128),
  mkCountry('Bosnia and Herzegovina', 'BA', 62, 122),
  mkCountry('Albania', 'AL', 65, 128),
  mkCountry('Moldova', 'MD', 62, 122),
  mkCountry('Georgia', 'GE', 58, 115),
  mkCountry('Turkey', 'TR', 57, 112),
  mkCountry('South Africa', 'ZA', 55, 108),
  mkCountry('Russia', 'RU', 56, 110),
  mkCountry('China', 'CN', 50, 99),
  mkCountry('Thailand', 'TH', 60, 119),
  mkCountry('Vietnam', 'VN', 28, 56),
  mkCountry('Indonesia', 'ID', 38, 76),
  mkCountry('Philippines', 'PH', 36, 71),
  mkCountry('Kazakhstan', 'KZ', 41, 81),
  mkCountry('Saudi Arabia', 'SA', 47, 92),
  mkCountry('Qatar', 'QA', 56, 110),
  mkCountry('Kuwait', 'KW', 52, 102),
  mkCountry('Bahrain', 'BH', 53, 105),
  mkCountry('Oman', 'OM', 50, 99),
  mkCountry('Jordan', 'JO', 25, 50),
  mkCountry('Lebanon', 'LB', 23, 45),
  mkCountry('Egypt', 'EG', 26, 51),
  mkCountry('Morocco', 'MA', 32, 64),
  mkCountry('Tunisia', 'TN', 33, 65),
  mkCountry('Kenya', 'KE', 36, 72),
  mkCountry('Ghana', 'GH', 33, 65),
  mkCountry('Senegal', 'SN', 34, 67),
  mkCountry('Nigeria', 'NG', 24, 46),
  mkCountry('Ethiopia', 'ET', 23, 45),
  mkCountry('Uganda', 'UG', 33, 65),
  mkCountry('Tanzania', 'TZ', 36, 72),
  mkCountry('Rwanda', 'RW', 33, 66),
  mkCountry('Algeria', 'DZ', 26, 51),
  mkCountry('India', 'IN', 32, 62),
  mkCountry('Sri Lanka', 'LK', 22, 43),
  mkCountry('Bangladesh', 'BD', 21, 42),
  mkCountry('Nepal', 'NP', 21, 42),
  mkCountry('Pakistan', 'PK', 20, 38),
  mkCountry('Iran', 'IR', 22, 44),
  mkCountry('Iraq', 'IQ', 16, 31),
  mkCountry('Yemen', 'YE', 17, 33),
  mkCountry('Syria', 'SY', 15, 29),
  mkCountry('Afghanistan', 'AF', 13, 26),
  mkCountry('Somalia', 'SO', 18, 35),
  mkCountry('North Korea', 'KP', 21, 41),
  mkCountry('Cuba', 'CU', 32, 63),
  mkCountry('Venezuela', 'VE', 65, 128),
  mkCountry('Colombia', 'CO', 65, 128),
  mkCountry('Peru', 'PE', 70, 136),
  mkCountry('Ecuador', 'EC', 50, 99),
  mkCountry('Bolivia', 'BO', 41, 82),
  mkCountry('Paraguay', 'PY', 70, 138),
  mkCountry('Dominican Republic', 'DO', 35, 70),
  mkCountry('Jamaica', 'JM', 45, 89),
  mkCountry('Bahamas', 'BS', 78, 154),
];

// Sort alphabetically and build an indexed map for fast lookup
COUNTRY_LIST.sort((a, b) => a.name.localeCompare(b.name));

export const COUNTRIES_ACCESS: Record<string, CountryAccess> = COUNTRY_LIST.reduce(
  (acc, c) => {
    acc[c.code] = c;
    return acc;
  },
  {} as Record<string, CountryAccess>,
);

export const COUNTRIES_LIST: CountryAccess[] = COUNTRY_LIST;

export const PROFILE_SLIDES: ProfileSlide[] = [
  {
    key: 'cuisine',
    label: 'Culinary curiosity',
    desc: 'How far outside your comfort zone will you eat?',
    low: 'Familiar only',
    high: "I'll eat anything",
    icon: '◉',
  },
  {
    key: 'distance',
    label: 'Travel distance',
    desc: 'How far from the nearest airport are you willing to go?',
    low: 'Under 1 hour',
    high: 'Days if needed',
    icon: '→',
  },
  {
    key: 'budget',
    label: 'Daily budget',
    desc: 'What can you spend per day, excluding flights?',
    low: '< $20/day',
    high: '$150+/day',
    icon: '$',
  },
  {
    key: 'risk',
    label: 'Risk tolerance',
    desc: 'How comfortable are you with unpredictability?',
    low: 'I need a plan',
    high: 'Plans ruin it',
    icon: '△',
  },
  {
    key: 'language',
    label: 'Language barrier',
    desc: 'Can you function where nobody speaks your language?',
    low: 'Need English',
    high: "I'll use my hands",
    icon: '◊',
  },
  {
    key: 'solitude',
    label: 'Solitude comfort',
    desc: 'How long can you be alone in a foreign place?',
    low: 'A few hours',
    high: 'Weeks, happily',
    icon: '○',
  },
];

// ── Destinations ──────────────────────────────────────────────────────────

export const DESTINATIONS: Destination[] = [
  {
    id: 'mestia',
    name: 'Mestia',
    country: 'Georgia',
    region: 'Svaneti, Upper Caucasus',
    coords: '43.0°N, 42.7°E',
    voiceNote:
      'You hear cowbells before you see the village. The bread here is baked in the ground.',
    voiceDuration: '0:15',
    prompts: [
      'Can you walk 6 hours uphill and call it a good day?',
      'Will you drink chacha with a stranger at 10am?',
    ],
    foodSpots: [
      {
        id: 'mestia-1',
        name: 'Window Kitchen',
        desc: 'A small, sign-less spot where a local family bakes khachapuri to order. Look for the steam rising from the third house past the stone tower.',
        funFact: "The owner uses a clay oven that's been in the same family for four generations.",
        submittedBy: '@hiker_olga',
        map: 'Third house past the stone tower, left side',
        type: 'Street food',
        priceLevel: 1,
        menu: [
          {
            name: 'Imeruli khachapuri',
            desc: 'Cheese-stuffed bread, single layer',
            price: '8 GEL',
          },
          { name: 'Acharuli khachapuri', desc: 'Boat-shaped, egg on top', price: '12 GEL' },
          { name: 'Lobiani', desc: 'Bean-stuffed flatbread', price: '7 GEL' },
          { name: 'Sweet kubdari', desc: 'Lamb and herbs in dough', price: '10 GEL' },
        ],
      },
      {
        id: 'mestia-2',
        name: "Laila's Kitchen",
        desc: "A homestyle place behind the police station serving Svan kubdari — the regional meat-stuffed bread that's distinct from the rest of Georgia.",
        funFact:
          'Kubdari was traditionally a long-trek food because it stays edible for three days unrefrigerated.',
        submittedBy: '@bread_atlas',
        map: 'Behind the police station, wooden gate',
        type: 'Home kitchen',
        priceLevel: 1,
        menu: [
          { name: 'Beef kubdari', desc: 'Ground beef, blue fenugreek, onion', price: '15 GEL' },
          { name: 'Lamb kubdari', desc: 'House specialty, slow-cooked filling', price: '18 GEL' },
          { name: 'Matsoni soup', desc: 'Cold yogurt soup with herbs', price: '9 GEL' },
          { name: 'Walnut sauce plate', desc: 'Cold appetizer with bread', price: '12 GEL' },
        ],
      },
      {
        id: 'mestia-3',
        name: 'Tower Cellar Wine Bar',
        desc: "Cellar tasting room beneath a Svan tower. Wine is fermented in qvevri — buried clay vessels — using a method UNESCO has called the world's oldest still in use.",
        funFact:
          "Some of the qvevri here are over 80 years old. They're never washed, only rinsed.",
        submittedBy: '@wine_passport',
        map: 'Below the Svan tower near the museum',
        type: 'Wine cellar',
        priceLevel: 2,
        menu: [
          { name: 'Saperavi flight', desc: 'Three reds, qvevri-aged', price: '25 GEL' },
          { name: 'Rkatsiteli amber', desc: 'Skin-contact white', price: '30 GEL' },
          { name: 'Cheese & sulguni board', desc: 'Local pairings', price: '22 GEL' },
          { name: 'Chacha shot', desc: 'Grape brandy, house-distilled', price: '8 GEL' },
        ],
      },
      {
        id: 'mestia-4',
        name: 'Café Laila',
        desc: "The closest thing to a town square. Traveler-leaning menu with Georgian classics. Reliable WiFi, which doesn't matter once you sit down.",
        funFact: 'Three generations of the same family have run a café on this corner since 1968.',
        submittedBy: '@trail_notes',
        map: 'Central square, opposite the post office',
        type: 'Café',
        priceLevel: 2,
        menu: [
          { name: 'Khinkali (8 pcs)', desc: 'Hand-pleated soup dumplings', price: '18 GEL' },
          { name: 'Mtsvadi', desc: 'Skewered pork over vine charcoal', price: '24 GEL' },
          { name: 'Eggplant with walnut', desc: 'Cold rolls, classic Georgian', price: '16 GEL' },
          { name: 'Tarragon soda', desc: 'Bright green, very strong', price: '5 GEL' },
        ],
      },
      {
        id: 'mestia-5',
        name: 'Honey & Bread Stall',
        desc: 'Roadside stall on the way to Ushguli selling raw mountain honey, fresh sulguni cheese, and rye bread baked that morning. The vendor is the beekeeper.',
        funFact:
          'Svan honey is unusually dark because the bees forage on rhododendron above 2000m.',
        submittedBy: '@slowmile',
        map: 'Roadside, 8km past Mestia toward Ushguli',
        type: 'Roadside stall',
        priceLevel: 1,
        menu: [
          { name: 'Mountain honey jar', desc: '500g, take-away', price: '20 GEL' },
          { name: 'Sulguni round', desc: 'Smoked, 250g', price: '10 GEL' },
          { name: 'Rye loaf', desc: 'Whole, daily-baked', price: '5 GEL' },
        ],
      },
      {
        id: 'mestia-6',
        name: 'Old Tower Tavern',
        desc: 'Long-table dinners in a stone room. Fixed nightly menu, no choices, no English on the wall. A handful of seats and a queue of regulars.',
        funFact:
          'The single long table seats 14. Strangers are seated next to each other on purpose.',
        submittedBy: '@feast_log',
        map: 'Below the eastern tower cluster',
        type: 'Tavern',
        priceLevel: 2,
        menu: [
          { name: 'Set dinner', desc: '5 courses, fixed nightly', price: '55 GEL' },
          { name: 'Wine pairing', desc: 'Three pours', price: '30 GEL' },
          { name: 'Dessert tasting', desc: 'Pelamushi & churchkhela', price: '12 GEL' },
        ],
      },
    ],
    friction: {
      transport: '4hr marshrutka from Zugdidi, unpaved last hour',
      language: 'Georgian/Svan, almost no English',
      connectivity: 'Intermittent 3G',
    },
    frictionLevel: 72,
    trivia: "The local word for 'stranger' is the same word as 'guest.'",
    deniedCount: 3,
    visaProb: { IN: 87, NO: 99, NG: 72, PK: 65, US: 99, SY: 31 },
    bestMonths: 'Jun–Sep',
    avgTemp: '18°C summer',
    currency: 'Georgian Lari (GEL)',
    flightHub: 'Kutaisi (KUT)',
    travelPlan: {
      flights: {
        from: 'DEL',
        to: 'KUT',
        airline: 'Wizz Air via Istanbul',
        duration: '9h 40m',
        stops: 1,
        price: '₹18,400',
      },
      hotels: [
        {
          name: 'Svan Guesthouse',
          type: 'Family homestay',
          price: '₹1,200/night',
          desc: "Stone house, shared bathroom, dinner included. The family speaks zero English and it doesn't matter.",
        },
        {
          name: 'Hotel Tetnuldi',
          type: 'Budget hotel',
          price: '₹2,800/night',
          desc: "The only place with reliable WiFi. You won't need it.",
        },
      ],
      itinerary: [
        {
          day: 1,
          title: 'Arrive & orient',
          desc: 'Marshrutka from Kutaisi. Arrive dazed. Walk the village. Find the bread window. Sleep early.',
        },
        {
          day: 2,
          title: 'Ushguli trek',
          desc: "6-hour hike to Europe's highest continuously inhabited village. Pack water. The views will make you forget your legs.",
        },
        {
          day: 3,
          title: 'The towers',
          desc: "Explore Svan defensive towers. Visit the ethnographic museum. Get invited to someone's house for chacha. Say yes.",
        },
        {
          day: 4,
          title: 'Get lost on purpose',
          desc: "No plan. Walk a direction. See what's there. This is the day the app goes dark.",
        },
        {
          day: 5,
          title: 'Departure',
          desc: "Morning marshrutka back. You'll want to stay. Everyone does.",
        },
      ],
      itineraryVariants: {
        classic: [
          {
            day: 1,
            title: 'Arrive & orient',
            desc: 'Marshrutka from Kutaisi. Walk the village. Find the bread window. Sleep early.',
          },
          {
            day: 2,
            title: 'Ushguli trek',
            desc: "6-hour hike to Europe's highest inhabited village. Pack water.",
          },
          {
            day: 3,
            title: 'The towers',
            desc: 'Explore Svan towers. Ethnographic museum. Chacha with strangers.',
          },
          {
            day: 4,
            title: 'Get lost on purpose',
            desc: 'No plan. Walk a direction. The app goes dark today.',
          },
          { day: 5, title: 'Departure', desc: 'Morning marshrutka back to Kutaisi.' },
        ],
        adventure: [
          {
            day: 1,
            title: 'Arrive & gear up',
            desc: 'Land in Kutaisi. Check trekking gear at Café Laila. Sleep early.',
          },
          {
            day: 2,
            title: 'Mestia → Chuberi traverse',
            desc: 'Multi-day hut trek begins. 14km, 1100m elevation gain.',
          },
          {
            day: 3,
            title: 'Glacier day',
            desc: 'Ascend toward Chalaadi glacier. Ice axe optional, weather permitting.',
          },
          {
            day: 4,
            title: 'Ushguli via the high pass',
            desc: 'Cross Latpari pass on horseback. Sleep in Ushguli.',
          },
          {
            day: 5,
            title: 'Descend & depart',
            desc: 'Truck down to Mestia, marshrutka to Kutaisi the next morning.',
          },
        ],
        relaxed: [
          {
            day: 1,
            title: 'Arrive & rest',
            desc: 'Slow morning. Settle into your guesthouse. Eat khachapuri.',
          },
          {
            day: 2,
            title: 'Village wander',
            desc: 'Walk the village in figure-eights. Find the bread window. Find the wine cellar.',
          },
          {
            day: 3,
            title: 'Museum day',
            desc: 'Mikhail Khergiani ethnographic museum. Long lunch. Read in the square.',
          },
          {
            day: 4,
            title: 'Honey road',
            desc: 'Easy walk along the Ushguli road. Stop at the honey stall. Turn around.',
          },
          {
            day: 5,
            title: 'Departure',
            desc: "Morning marshrutka. Buy two jars of honey. Don't forget the cheese.",
          },
        ],
      },
    },
  },
  {
    id: 'harar',
    name: 'Harar',
    country: 'Ethiopia',
    region: 'Harari Region, Eastern Highlands',
    coords: '9.3°N, 42.1°E',
    voiceNote:
      'The hyenas come at dusk. The man who feeds them learned from his father, who learned from his.',
    voiceDuration: '0:18',
    prompts: [
      'Can you drink coffee that takes an hour to prepare?',
      'Are you comfortable in a city with 362 alleyways and no map?',
    ],
    foodSpots: [
      {
        id: 'harar-1',
        name: 'Shoa Gate Injera House',
        desc: 'Family-run spot near the Shoa Gate serving traditional injera plates. Diners share a single platter; eating with the right hand only is the local custom.',
        funFact:
          'The teff used in injera is the smallest cereal grain in the world — it takes 150 grains to weigh as much as a single grain of wheat.',
        submittedBy: '@horn_of_africa',
        map: 'Near the Shoa Gate, downhill, follow the spice smell',
        type: 'Local restaurant',
        priceLevel: 1,
        menu: [
          { name: 'Injera firfir', desc: 'Torn injera in spiced sauce', price: '60 ETB' },
          { name: 'Kitfo', desc: 'Raw beef minced with mitmita and butter', price: '180 ETB' },
          { name: 'Beyaynetu', desc: 'Vegetarian sampler — 7 sides on injera', price: '120 ETB' },
          { name: 'Tibs', desc: 'Pan-fried beef with onion and rosemary', price: '150 ETB' },
        ],
      },
      {
        id: 'harar-2',
        name: "Abdullahi's Coffee Ceremony",
        desc: 'A traditional Ethiopian coffee ceremony performed in a private home. Green beans roasted in front of you, brewed in three rounds over roughly two hours.',
        funFact:
          "Refusing the third round (called 'baraka', meaning blessing) is considered an insult here. Pace yourself.",
        submittedBy: '@slow_brew',
        map: 'Inside the old city, ask anyone for Abdullahi',
        type: 'Coffee ceremony',
        priceLevel: 1,
        menu: [
          { name: 'Full ceremony', desc: 'Three rounds, popcorn, incense', price: '100 ETB' },
          { name: 'Single bunna', desc: 'First round, traditional clay cup', price: '30 ETB' },
          { name: 'Sugar service', desc: 'Add 2 spoons per cup, local style', price: 'Free' },
        ],
      },
      {
        id: 'harar-3',
        name: 'Night Market Juice Stand',
        desc: 'Open-air stall in the main market square serving layered fruit juices in tall glasses. The vendor has been working this corner for two decades.',
        funFact: "The signature 'spris' is layered by density alone — no spoon, no tricks.",
        submittedBy: '@market_lights',
        map: 'Main market square after 7pm',
        type: 'Street vendor',
        priceLevel: 1,
        menu: [
          { name: 'Spris (layered)', desc: 'Avocado, mango, papaya, guava', price: '50 ETB' },
          { name: 'Avocado-mango', desc: 'Two-layer classic', price: '35 ETB' },
          { name: 'Pure papaya', desc: 'Cold, fresh', price: '25 ETB' },
        ],
      },
      {
        id: 'harar-4',
        name: 'Hyena Gate Café',
        desc: 'Open café near the eastern wall where many travelers gather before the dusk hyena feeding. Simple breakfast and lunch fare, very strong coffee.',
        funFact:
          "Hyenas have been ritually fed at this gate for over 200 years to keep them from the city's livestock.",
        submittedBy: '@dusk_walks',
        map: 'Outside the eastern wall, by the hyena viewing area',
        type: 'Café',
        priceLevel: 2,
        menu: [
          { name: 'Ful with bread', desc: 'Mashed fava beans, boiled egg', price: '70 ETB' },
          { name: 'Shiro tegabino', desc: 'Spiced chickpea stew, clay pot', price: '90 ETB' },
          { name: 'Sambusa (4 pcs)', desc: 'Fried lentil pastries', price: '60 ETB' },
          { name: 'Macchiato', desc: 'Italian-Ethiopian, very dense', price: '25 ETB' },
        ],
      },
      {
        id: 'harar-5',
        name: 'Adare Rooftop',
        desc: 'A small rooftop place inside the old city walls. Distant view of the minarets at sunset. Menu is short and changes weekly.',
        funFact:
          'Harar has 99 mosques inside the walls — one of the highest densities of religious buildings in the world.',
        submittedBy: '@minaret_count',
        map: 'Old city, near the Jami mosque, climb three flights',
        type: 'Rooftop kitchen',
        priceLevel: 2,
        menu: [
          { name: 'Lamb tibs platter', desc: 'With injera and ayib', price: '200 ETB' },
          { name: 'Vegetable shiro', desc: 'Vegan, served bubbling', price: '110 ETB' },
          { name: 'Tej', desc: 'Honey wine, served in berele flask', price: '80 ETB' },
        ],
      },
      {
        id: 'harar-6',
        name: 'Spice Market Lunch',
        desc: 'Lunch counter inside the spice market — eat sitting on a low bench between sacks of cardamom and chili. The cook has been there since the 1980s.',
        funFact:
          "The blend you'll smell in the air is berbere — at least 16 spices, never the same twice.",
        submittedBy: '@spice_route',
        map: 'Inside the central spice market',
        type: 'Market lunch',
        priceLevel: 1,
        menu: [
          { name: 'Misir wat', desc: 'Red lentil stew, very spicy', price: '75 ETB' },
          { name: 'Atkilt wat', desc: 'Cabbage, carrot, potato', price: '65 ETB' },
          { name: 'Berbere take-home', desc: '100g, hand-blended', price: '120 ETB' },
        ],
      },
    ],
    friction: {
      transport: '1hr flight from Addis or 8hr bus through the Rift Valley',
      language: 'Harari/Amharic, minimal English',
      connectivity: 'Decent 4G in center, nothing outside',
    },
    frictionLevel: 68,
    trivia: 'This city has been trading coffee for 600 years. Starbucks has existed for 54.',
    deniedCount: 7,
    visaProb: { IN: 91, NO: 97, NG: 78, PK: 70, US: 97, SY: 25 },
    bestMonths: 'Oct–Feb',
    avgTemp: '24°C',
    currency: 'Ethiopian Birr (ETB)',
    flightHub: 'Dire Dawa (DIR)',
    travelPlan: {
      flights: {
        from: 'DEL',
        to: 'DIR',
        airline: 'Ethiopian Airlines via Addis',
        duration: '8h 20m',
        stops: 1,
        price: '₹24,600',
      },
      hotels: [
        {
          name: 'Ras Hotel Harar',
          type: 'Heritage hotel',
          price: '₹1,600/night',
          desc: 'Colonial era building in the old city. Creaky floors and the best rooftop view of the minarets.',
        },
        {
          name: 'Rewda homestay',
          type: 'Family home',
          price: '₹800/night',
          desc: 'Sleeping on traditional mats. Morning coffee ceremony included. The grandmother will adopt you.',
        },
      ],
      itinerary: [
        {
          day: 1,
          title: 'Enter the walls',
          desc: "Arrive from Dire Dawa. Walk through the Shoa Gate. Get lost immediately. That's correct.",
        },
        {
          day: 2,
          title: 'The 362 alleyways',
          desc: "Wander the old city. Visit the Harari museum. Buy spices you can't name. Eat injera until you can't.",
        },
        {
          day: 3,
          title: 'Hyena feeding',
          desc: 'At dusk, go to the eastern wall. The Hyena Man will hand you raw meat on a stick. You hold it in your teeth. A hyena takes it from your mouth. This is real.',
        },
        {
          day: 4,
          title: 'Coffee and nothing else',
          desc: 'Spend the entire day doing coffee ceremonies. Three rounds each. At least two houses. Talk to everyone.',
        },
        {
          day: 5,
          title: 'Departure',
          desc: "Bus to Dire Dawa at dawn. The city gets smaller in your window. You'll think about the hyenas for years.",
        },
      ],
      itineraryVariants: {
        classic: [
          {
            day: 1,
            title: 'Enter the walls',
            desc: 'Arrive from Dire Dawa. Walk through the Shoa Gate.',
          },
          { day: 2, title: 'The 362 alleyways', desc: 'Old city, Harari museum, spice market.' },
          { day: 3, title: 'Hyena feeding', desc: 'Eastern wall at dusk. The Hyena Man.' },
          { day: 4, title: 'Coffee day', desc: 'Two ceremonies. Three rounds each.' },
          { day: 5, title: 'Departure', desc: 'Bus to Dire Dawa at dawn.' },
        ],
        adventure: [
          {
            day: 1,
            title: 'Land & ride',
            desc: 'Fly to Dire Dawa. Hire a driver into the Chercher highlands.',
          },
          {
            day: 2,
            title: 'Babile camel market',
            desc: 'Sunday-only camel auction 30km out of town.',
          },
          {
            day: 3,
            title: 'Hyena overnight',
            desc: 'Walk the wall at dusk. Sleep with the gates open.',
          },
          {
            day: 4,
            title: 'Old city by horse',
            desc: 'Hire a guide on horseback through the surrounding villages.',
          },
          { day: 5, title: 'Departure', desc: 'Long bus through the Rift Valley back to Addis.' },
        ],
        relaxed: [
          {
            day: 1,
            title: 'Slow arrival',
            desc: 'Fly to Dire Dawa. Drive in. Long lunch in the old city.',
          },
          {
            day: 2,
            title: 'Coffee morning',
            desc: 'One ceremony, three rounds. Read on the rooftop after.',
          },
          {
            day: 3,
            title: 'Wall walk',
            desc: 'Slow loop of the city walls. Hyenas at sunset only if you feel like it.',
          },
          {
            day: 4,
            title: 'Spice market',
            desc: 'Buy berbere, mitmita. Eat lunch among the sacks.',
          },
          { day: 5, title: 'Departure', desc: 'Late drive to Dire Dawa. Afternoon flight.' },
        ],
      },
    },
  },
  {
    id: 'karakol',
    name: 'Karakol',
    country: 'Kyrgyzstan',
    region: 'Issyk-Kul Province, Tian Shan',
    coords: '42.5°N, 78.4°E',
    voiceNote: "The mountains here don't care about you. That's why they're beautiful.",
    voiceDuration: '0:12',
    prompts: [
      'Can you eat horse meat and not make it weird?',
      'Do you know how to be cold and happy at the same time?',
    ],
    foodSpots: [
      {
        id: 'karakol-1',
        name: 'Dungan Ashlan-Fu House',
        desc: "Cold noodles in vinegar broth — a Dungan specialty brought to Kyrgyzstan in the 19th century. The cook follows a recipe that hasn't changed in three decades.",
        funFact:
          'The Dungan people are descendants of Hui Muslims who fled imperial China in 1877.',
        submittedBy: '@noodle_atlas',
        map: 'Behind the central bazaar, blue metal door',
        type: 'Home restaurant',
        priceLevel: 1,
        menu: [
          {
            name: 'Ashlan-fu (single)',
            desc: 'Cold noodles, vinegar broth, peas',
            price: '60 KGS',
          },
          { name: 'Ashlan-fu (double)', desc: 'Two bowls, hand-pulled extra', price: '100 KGS' },
          { name: 'Pirozhki side', desc: 'Fried potato bun, traditional pair', price: '20 KGS' },
        ],
      },
      {
        id: 'karakol-2',
        name: 'Bazaar Samsa Stand',
        desc: 'Tandoor-baked lamb pastries from a single stall at the south entrance of the central bazaar. They sell out by 11am on most days.',
        funFact:
          'The clay tandoor here is half buried in the ground — locals say the deeper the oven, the better the seal.',
        submittedBy: '@morning_walks',
        map: 'Central bazaar, south entrance, first stall on right',
        type: 'Bazaar stall',
        priceLevel: 1,
        menu: [
          { name: 'Lamb samsa', desc: 'Onion, fat, tandoor-baked', price: '50 KGS' },
          { name: 'Beef samsa', desc: 'Slightly leaner', price: '45 KGS' },
          { name: 'Pumpkin samsa', desc: 'Seasonal, autumn only', price: '40 KGS' },
        ],
      },
      {
        id: 'karakol-3',
        name: 'Besh Barmak Family House',
        desc: 'Five-finger noodles with horse meat — a Kyrgyz centerpiece dish. Eaten with the right hand from a shared platter. Most guesthouses can arrange it on request.',
        funFact:
          "'Besh barmak' literally means 'five fingers'. Forks are recent and considered slightly silly here.",
        submittedBy: '@steppe_table',
        map: 'Ask your guesthouse — most arrange it directly',
        type: 'Home cooking',
        priceLevel: 2,
        menu: [
          { name: 'Besh barmak set', desc: 'Boiled horse, noodles, broth', price: '350 KGS' },
          { name: 'Kymyz', desc: "Fermented mare's milk, cold", price: '60 KGS' },
          { name: 'Borsok bread', desc: 'Fried dough cubes, table snack', price: '30 KGS' },
        ],
      },
      {
        id: 'karakol-4',
        name: 'Cafe Zarina',
        desc: 'Quiet, family-run café two blocks from the bazaar. Russian-Kyrgyz menu, low prices, good for sitting alone with a book and watching snow fall.',
        funFact:
          "The owner's mother was the head cook on a Soviet expedition train through Central Asia.",
        submittedBy: '@bookbench',
        map: 'Two blocks west of the bazaar, behind the Lenin statue',
        type: 'Café',
        priceLevel: 2,
        menu: [
          { name: 'Lagman', desc: 'Hand-pulled noodles, lamb, vegetables', price: '180 KGS' },
          { name: 'Manty (5 pcs)', desc: 'Steamed dumplings, sour cream', price: '150 KGS' },
          { name: 'Plov', desc: 'Carrot-rice, raisins, lamb', price: '170 KGS' },
          { name: 'Black tea pot', desc: 'Bottomless', price: '40 KGS' },
        ],
      },
      {
        id: 'karakol-5',
        name: 'Yurt Camp Breakfast',
        desc: "Open-air breakfast served at the Tagaytay yurt camp at dawn. Fresh bread, butter, jam, cream, and honey from the neighbor's bees.",
        funFact:
          'The bread is baked in the same kazan used to boil meat for dinner — flavor crosses over by design.',
        submittedBy: '@yurt_dawn',
        map: 'Tagaytay yurt camp, 12km outside Karakol',
        type: 'Yurt breakfast',
        priceLevel: 1,
        menu: [
          { name: 'Full breakfast', desc: 'Bread, kaymak, jam, honey, eggs', price: '200 KGS' },
          { name: 'Kaymak only', desc: 'Thick mountain cream, with bread', price: '70 KGS' },
          { name: 'Mountain honey', desc: '250g jar', price: '180 KGS' },
        ],
      },
      {
        id: 'karakol-6',
        name: 'Issyk-Kul Smoked Fish',
        desc: 'Lakeside shacks selling smoked osman and chebak from the lake. Pulled from the smoker in the afternoon and eaten with bread on a wooden bench.',
        funFact:
          'Lake Issyk-Kul never freezes despite being 1600m up — locals say the water remembers the sun.',
        submittedBy: '@lake_eats',
        map: 'Lakeshore, 30 min from Karakol toward Cholpon-Ata',
        type: 'Lakeside shack',
        priceLevel: 1,
        menu: [
          { name: 'Smoked osman', desc: 'Whole fish, paper-wrapped', price: '200 KGS' },
          { name: 'Smoked chebak', desc: 'Smaller, two per portion', price: '120 KGS' },
          { name: 'Bread + onion', desc: 'On the side, fixed price', price: '30 KGS' },
        ],
      },
    ],
    friction: {
      transport: '7hr shared taxi from Bishkek, mountain passes',
      language: 'Kyrgyz/Russian, very little English',
      connectivity: 'WiFi in town, nothing in valleys',
    },
    frictionLevel: 65,
    trivia: "More horses than cars. Nobody here thinks that's unusual.",
    deniedCount: 1,
    visaProb: { IN: 94, NO: 99, NG: 80, PK: 75, US: 99, SY: 40 },
    bestMonths: 'Jul–Sep',
    avgTemp: '22°C summer',
    currency: 'Kyrgyz Som (KGS)',
    flightHub: 'Bishkek Manas (FRU)',
    travelPlan: {
      flights: {
        from: 'DEL',
        to: 'FRU',
        airline: 'Air Manas via Almaty',
        duration: '6h 10m',
        stops: 1,
        price: '₹15,200',
      },
      hotels: [
        {
          name: 'Tagaytay Yurt Camp',
          type: 'Yurt stay',
          price: '₹900/night',
          desc: 'Felt walls, wood stove, total silence except the river. Breakfast is fresh bread and honey from the neighbor.',
        },
        {
          name: 'Duet Hostel',
          type: 'Budget hostel',
          price: '₹600/night',
          desc: "Run by two sisters who will plan your entire trip if you let them. Don't let them. Get lost instead.",
        },
      ],
      itinerary: [
        {
          day: 1,
          title: 'The long road in',
          desc: "Shared taxi from Bishkek. You'll stop for roadside kymyz (fermented mare's milk). Drink it.",
        },
        {
          day: 2,
          title: 'Jyrgalan Valley',
          desc: 'Hike into the valley. No trails marked. Follow the river. Find the hot spring the locals use.',
        },
        {
          day: 3,
          title: 'Bazaar day',
          desc: "Central market. Buy felt, eat samsa, watch the animal trading. Nobody's performing for you. This is Tuesday.",
        },
        {
          day: 4,
          title: 'Horse day',
          desc: 'Rent a horse. Ride toward the mountains. The horse knows where to go better than you do.',
        },
        {
          day: 5,
          title: 'Departure',
          desc: "Shared taxi back. Seven hours of mountain passes. You'll sleep through the best views and dream about the ones you saw awake.",
        },
      ],
      itineraryVariants: {
        classic: [
          { day: 1, title: 'The long road in', desc: 'Shared taxi from Bishkek. Stop for kymyz.' },
          { day: 2, title: 'Jyrgalan Valley', desc: 'Day hike, hot spring, no trails marked.' },
          { day: 3, title: 'Bazaar day', desc: 'Central market, samsa, animal trading.' },
          { day: 4, title: 'Horse day', desc: "Ride toward the mountains. Don't steer." },
          { day: 5, title: 'Departure', desc: 'Shared taxi back. Mountain passes.' },
        ],
        adventure: [
          { day: 1, title: 'Bishkek → Karakol', desc: 'Stock up gear in town.' },
          {
            day: 2,
            title: 'Ala-Kul trek day 1',
            desc: 'Trailhead to Sirota Camp. 14km, river crossings.',
          },
          {
            day: 3,
            title: 'Ala-Kul Lake day',
            desc: 'Climb the pass. Camp at 3500m next to the lake.',
          },
          {
            day: 4,
            title: 'Altyn Arashan descent',
            desc: 'Down through the canyon. Hot springs at the end.',
          },
          { day: 5, title: 'Departure', desc: 'Sore. Triumphant. Shared taxi back.' },
        ],
        relaxed: [
          { day: 1, title: 'Slow arrival', desc: 'Late bus from Bishkek. Long dinner in Karakol.' },
          { day: 2, title: 'Lake day', desc: 'Drive to Issyk-Kul shore. Smoked fish lunch. Read.' },
          { day: 3, title: 'Bazaar morning', desc: 'Slow walk through the market. Buy felt.' },
          {
            day: 4,
            title: 'Yurt overnight',
            desc: 'Out to Tagaytay. Sleep early. Wake before the sun.',
          },
          { day: 5, title: 'Departure', desc: 'Mid-morning return. Light lunch in Bishkek.' },
        ],
      },
    },
  },
  {
    id: 'tsenkher',
    name: 'Tsenkher',
    country: 'Mongolia',
    region: 'Arkhangai, Khangai Mountains',
    coords: '47.4°N, 101.4°E',
    voiceNote: 'The hot spring runs all year. The sky here goes on long after the day stops.',
    voiceDuration: '0:14',
    prompts: [
      'Can you sleep in a yurt with strangers and call it Wednesday?',
      'Are you OK with no signal for three days?',
    ],
    foodSpots: [
      {
        id: 'tsenkher-1',
        name: 'Ger camp dinner',
        desc: 'Boiled mutton with hand-pulled noodles served family-style around a stove. Vegetables are rare; meat is the meal.',
        funFact:
          'Mongolian hospitality demands you accept whatever is offered — refusing food is a stronger taboo than overstaying.',
        submittedBy: '@steppe_walks',
        map: 'Any ger camp around the springs',
        type: 'Ger kitchen',
        priceLevel: 2,
        menu: [
          { name: 'Tsuivan', desc: 'Hand-pulled noodles with mutton', price: '16,000 MNT' },
          {
            name: 'Khorkhog',
            desc: 'Mutton cooked with hot stones inside the pot',
            price: '45,000 MNT',
          },
          { name: 'Buuz (5 pcs)', desc: 'Steamed mutton dumplings', price: '12,000 MNT' },
          { name: 'Suutei tsai', desc: 'Salted milk tea, bottomless', price: 'Free with meal' },
        ],
      },
      {
        id: 'tsenkher-2',
        name: 'Hot spring kitchen',
        desc: 'A small wooden cabin near the main pool serving simple noodles and bread to bathers throughout the day.',
        funFact:
          "The springs come out of the ground at 86°C — they're cooled with cold stream water before bathing.",
        submittedBy: '@warm_water',
        map: 'Bathhouse complex, lower pool',
        type: 'Bathhouse café',
        priceLevel: 1,
        menu: [
          { name: 'Bantan', desc: 'Hot mutton-flour porridge', price: '9,000 MNT' },
          { name: 'Boortsog', desc: 'Fried dough biscuits, with butter', price: '5,000 MNT' },
          { name: 'Aaruul plate', desc: 'Dried curd, traditional snack', price: '8,000 MNT' },
        ],
      },
      {
        id: 'tsenkher-3',
        name: 'Nomad family lunch',
        desc: 'Pre-arranged lunch with a herding family in their summer ger. Whatever is on the stove that day.',
        funFact:
          'Families move ger 2-4 times per year following grazing — the hosts you eat with may not be there next month.',
        submittedBy: '@gobi_drift',
        map: 'Ask camp host to arrange — usually 30 min ride',
        type: 'Family ger',
        priceLevel: 2,
        menu: [
          { name: 'Set lunch', desc: 'Whatever the family is making', price: '30,000 MNT' },
          { name: 'Airag', desc: "Fermented mare's milk, mildly alcoholic", price: '10,000 MNT' },
        ],
      },
      {
        id: 'tsenkher-4',
        name: 'Tsetserleg market stall',
        desc: 'Town market stall on the way to the springs, selling smoked dried meat (borts) and yak-butter for the road.',
        funFact:
          'Mongolians have been air-drying meat in winter for transport since the time of Genghis Khan.',
        submittedBy: '@market_steppe',
        map: 'Tsetserleg central market, north end',
        type: 'Market stall',
        priceLevel: 1,
        menu: [
          { name: 'Borts (200g)', desc: 'Air-dried beef, take-away', price: '20,000 MNT' },
          { name: 'Yak butter', desc: 'Fresh, by weight', price: '12,000 MNT/100g' },
        ],
      },
    ],
    friction: {
      transport: '8hr drive from UB on rough roads',
      language: 'Mongolian only',
      connectivity: 'No signal beyond Tsetserleg',
    },
    frictionLevel: 78,
    trivia: 'There are more horses than people in this province.',
    deniedCount: 0,
    visaProb: { IN: 78, NO: 95, NG: 60, PK: 50, US: 95, SY: 30, GB: 95, DE: 95, JP: 99, AU: 92 },
    bestMonths: 'Jun–Sep',
    avgTemp: '16°C summer',
    currency: 'Mongolian Tögrög (MNT)',
    flightHub: 'Ulaanbaatar (UBN)',
    travelPlan: {
      flights: {
        from: 'DEL',
        to: 'UBN',
        airline: 'MIAT via Beijing',
        duration: '11h 20m',
        stops: 1,
        price: '₹42,000',
      },
      hotels: [
        {
          name: 'Tsenkher Jiguur Resort',
          type: 'Ger camp',
          price: '₹2,400/night',
          desc: 'Wooden gers with stoves and hot-spring access. Half-board included.',
        },
        {
          name: 'Family homestay (Tsetserleg)',
          type: 'Family home',
          price: '₹900/night',
          desc: 'Soviet-era apartment in town; the family hosts you for the night before the long drive out.',
        },
      ],
      itinerary: [
        {
          day: 1,
          title: 'Ulaanbaatar → Tsetserleg',
          desc: 'Long drive west. Ovoo cairn stops along the road. Sleep in town.',
        },
        {
          day: 2,
          title: 'Out to the springs',
          desc: 'Final 90 min on dirt track. Settle into your ger. First soak at sunset.',
        },
        {
          day: 3,
          title: 'Steppe day',
          desc: 'Horse ride out with the camp herder. Lunch with a family. Return to soak.',
        },
        {
          day: 4,
          title: 'Empty day',
          desc: 'No plan. Walk the valley. Bathe twice. Watch the stars after dark.',
        },
        {
          day: 5,
          title: 'Departure',
          desc: 'Long drive back. The sky in your rear-view will stay with you.',
        },
      ],
    },
  },
  {
    id: 'suduroy',
    name: 'Suðuroy',
    country: 'Faroe Islands',
    region: 'Southernmost island',
    coords: '61.5°N, 6.8°W',
    voiceNote: 'The cliffs end the world. The sheep here outnumber the people six to one.',
    voiceDuration: '0:12',
    prompts: [
      'Can you tolerate three weather systems before lunch?',
      "Will you eat fish that's been wind-dried for six months?",
    ],
    foodSpots: [
      {
        id: 'suduroy-1',
        name: 'Hvalba quayside kitchen',
        desc: "A small quay-side dining room serving the day's catch. The owner is also the boat captain who brought it in.",
        funFact:
          "The Faroese still operate one of the world's last working whale-pilot communities — but most restaurants now serve only fish.",
        submittedBy: '@northsea_log',
        map: 'Hvalba harbor, blue building',
        type: 'Harbor kitchen',
        priceLevel: 3,
        menu: [
          { name: 'Catch of the day', desc: 'Cod or haddock, butter-poached', price: '180 DKK' },
          {
            name: 'Skerpikjøt plate',
            desc: 'Wind-dried mutton, dense and salty',
            price: '140 DKK',
          },
          { name: 'Black bread + cured cod', desc: 'Traditional starter', price: '85 DKK' },
          { name: 'Akvavit shot', desc: 'Caraway spirit, served cold', price: '55 DKK' },
        ],
      },
      {
        id: 'suduroy-2',
        name: 'Hov sheep farm dinner',
        desc: 'Farm-to-table set menu hosted in a stone farmhouse. Five courses of lamb prepared every way the family knows.',
        funFact:
          "Faroese sheep are smaller than mainland breeds because they've inbred on the islands for over a millennium.",
        submittedBy: '@sheep_count',
        map: 'Hov, follow signs from main road',
        type: 'Farm dinner',
        priceLevel: 4,
        menu: [
          {
            name: '5-course lamb tasting',
            desc: 'Tartare → wind-dried → roast → confit → liver',
            price: '450 DKK',
          },
          {
            name: 'Wine pairing',
            desc: 'Three pours from Nordic-friendly producers',
            price: '220 DKK',
          },
        ],
      },
      {
        id: 'suduroy-3',
        name: 'Tvøroyri bakery',
        desc: 'Town bakery making rye loaves and rye-cake every morning. Locals come early; tourists rarely find it.',
        funFact: "Rye in the Faroes is imported — wheat won't grow this far north.",
        submittedBy: '@early_bread',
        map: 'Tvøroyri main street, opposite the church',
        type: 'Bakery',
        priceLevel: 1,
        menu: [
          { name: 'Rye bread loaf', desc: 'Whole, dense, take-away', price: '45 DKK' },
          { name: 'Rye cake slice', desc: 'Sweet, with butter', price: '28 DKK' },
          { name: 'Coffee + cinnamon roll', desc: 'Standard order', price: '55 DKK' },
        ],
      },
      {
        id: 'suduroy-4',
        name: 'Sumba cliff café',
        desc: 'Tiny café perched at the southernmost cliff. Open only when the weather allows — about half the days a year.',
        funFact: 'On a clear day you can see Iceland, 450km north.',
        submittedBy: '@cliff_walks',
        map: 'Sumba village, end of the road',
        type: 'Cliff café',
        priceLevel: 2,
        menu: [
          { name: 'Fish soup', desc: 'Cream-based, cod chunks, potato', price: '110 DKK' },
          { name: 'Lamb sandwich', desc: 'Wind-dried mutton on rye', price: '95 DKK' },
          { name: 'Hot chocolate', desc: "With cream, you'll want it", price: '45 DKK' },
        ],
      },
    ],
    friction: {
      transport: '2hr ferry from Tórshavn, weather-dependent',
      language: 'Faroese, most speak English',
      connectivity: 'Reliable 4G in towns, none on cliffs',
    },
    frictionLevel: 58,
    trivia: 'Population 4,600. Sheep population: ~25,000.',
    deniedCount: 0,
    visaProb: { IN: 65, NO: 99, NG: 50, PK: 40, US: 95, SY: 22, GB: 95, DE: 99, JP: 95, AU: 90 },
    bestMonths: 'May–Aug',
    avgTemp: '12°C summer',
    currency: 'Faroese Króna (FOK)',
    flightHub: 'Vágar (FAE)',
    travelPlan: {
      flights: {
        from: 'DEL',
        to: 'FAE',
        airline: 'Atlantic Airways via Copenhagen',
        duration: '13h 30m',
        stops: 1,
        price: '₹68,000',
      },
      hotels: [
        {
          name: 'Hotel Tvøroyri',
          type: 'Town hotel',
          price: '₹6,500/night',
          desc: 'Old harbor hotel; rooms face the fjord; breakfast included.',
        },
        {
          name: 'Cliff guesthouse',
          type: 'Family-run',
          price: '₹4,800/night',
          desc: 'Three rooms in a cliffside house; the host bakes bread for breakfast and packs a lunch for the trail.',
        },
      ],
      itinerary: [
        {
          day: 1,
          title: 'Arrive via Tórshavn',
          desc: 'Fly to Vágar, drive across two undersea tunnels to catch the Suðuroy ferry.',
        },
        {
          day: 2,
          title: 'Cliff hike',
          desc: 'Walk the western cliffs from Hvalba to Sandvík. 14km, weather permitting.',
        },
        {
          day: 3,
          title: 'Sumba & the southern point',
          desc: 'Drive to the cliff café. Stand at the southernmost rock. Try not to get blown over.',
        },
        {
          day: 4,
          title: 'Inland day',
          desc: 'Visit the sheep farm. Eat the lamb dinner. Sleep early.',
        },
        { day: 5, title: 'Return', desc: 'Morning ferry back to Tórshavn. Afternoon flight home.' },
      ],
    },
  },
  {
    id: 'turtuk',
    name: 'Turtuk',
    country: 'India',
    region: 'Nubra Valley, Ladakh',
    coords: '34.8°N, 76.8°E',
    voiceNote: "We were Pakistan until 1971. The apricots here haven't changed since.",
    voiceDuration: '0:16',
    prompts: [
      'Can you sleep at 3000m and trust the sky?',
      "Will you eat from a stranger's hand the first time you meet?",
    ],
    foodSpots: [
      {
        id: 'turtuk-1',
        name: 'Balti family kitchen',
        desc: "A small dining room behind the village mosque. The matriarch cooks Balti specialties that don't appear in Indian guidebooks.",
        funFact:
          'Balti cuisine is older than the partition — it stretches back to the 14th-century trade route to Tibet.',
        submittedBy: '@high_passes',
        map: 'Past the wooden mosque, courtyard with apricot tree',
        type: 'Home kitchen',
        priceLevel: 1,
        menu: [
          { name: 'Balti khurba', desc: 'Buckwheat pancakes with walnut paste', price: '180 INR' },
          { name: 'Phating', desc: 'Apricot-stone soup', price: '150 INR' },
          { name: 'Bread + apricot oil', desc: 'Local breakfast staple', price: '120 INR' },
          { name: 'Butter tea', desc: 'Salted, served in wooden bowl', price: '60 INR' },
        ],
      },
      {
        id: 'turtuk-2',
        name: 'Apricot orchard lunch',
        desc: 'Open-air lunch under apricot trees in season. The same family that runs the homestay opens their orchard to guests.',
        funFact:
          "Turtuk's apricot variety is unique to this valley — 40 distinct sub-types are recognized by local growers.",
        submittedBy: '@stone_fruit',
        map: 'Walk uphill from the village square, follow the irrigation channel',
        type: 'Orchard table',
        priceLevel: 2,
        menu: [
          {
            name: 'Apricot kernel rice',
            desc: 'Local rice cooked in apricot kernel oil',
            price: '240 INR',
          },
          {
            name: 'Mixed apricot platter',
            desc: 'Fresh, dried, jam, kernel paste',
            price: '180 INR',
          },
          { name: 'Mok mok dumplings', desc: 'Steamed, with mint chutney', price: '200 INR' },
        ],
      },
      {
        id: 'turtuk-3',
        name: 'Polo ground tea stall',
        desc: 'Tin-roof tea shack at the edge of the polo ground. Glass cases of biscuits, sweet milky chai brewed all day.',
        funFact:
          "The polo ground here is older than the village's recognition as Indian territory.",
        submittedBy: '@chai_atlas',
        map: 'Polo ground, north edge',
        type: 'Tea stall',
        priceLevel: 1,
        menu: [
          { name: 'Kahwa', desc: 'Saffron-cardamom Kashmiri tea', price: '40 INR' },
          { name: 'Plain chai', desc: 'Sweet, milky', price: '20 INR' },
          { name: 'Biscuit plate', desc: 'Local bakery, mixed', price: '30 INR' },
        ],
      },
      {
        id: 'turtuk-4',
        name: 'Riverside grill',
        desc: 'Seasonal trout grill on the Shyok river bank. The fish is caught the morning of, salted, grilled over juniper.',
        funFact: 'The Shyok river crosses three nations within 200km of here.',
        submittedBy: '@river_walks',
        map: 'Walk down to the river, blue tarp, follow the smoke',
        type: 'Riverside grill',
        priceLevel: 2,
        menu: [
          { name: 'Grilled trout', desc: 'Whole fish, juniper-smoked', price: '450 INR' },
          { name: 'Rice & dal', desc: 'Side, basic but hot', price: '120 INR' },
          { name: 'Cold buttermilk', desc: 'Local lassi', price: '60 INR' },
        ],
      },
    ],
    friction: {
      transport: '5hr drive from Leh over Khardung La pass (5360m)',
      language: 'Balti, Urdu, broken Hindi',
      connectivity: 'BSNL only, intermittent',
    },
    frictionLevel: 70,
    trivia:
      'Until 1971, this village was in Pakistan. Some families still have relatives across the line of control.',
    deniedCount: 0,
    visaProb: { IN: 99, NO: 78, NG: 55, PK: 30, US: 80, SY: 30, GB: 82, DE: 82, JP: 82, AU: 80 },
    bestMonths: 'Jun–Sep',
    avgTemp: '14°C summer',
    currency: 'Indian Rupee (INR)',
    flightHub: 'Leh (IXL)',
    travelPlan: {
      flights: {
        from: 'DEL',
        to: 'IXL',
        airline: 'IndiGo direct',
        duration: '1h 25m',
        stops: 0,
        price: '₹6,800',
      },
      hotels: [
        {
          name: 'Turtuk Holiday Resort',
          type: 'Wooden lodge',
          price: '₹2,400/night',
          desc: 'Stone-and-wood rooms looking onto orchards. Heat is wood-burning; nights are cold.',
        },
        {
          name: 'Maha Homestay',
          type: 'Family home',
          price: '₹1,200/night',
          desc: "Three rooms in a Balti family's house; meals shared, bedding heavy quilts. The grandmother will not let you leave hungry.",
        },
      ],
      itinerary: [
        {
          day: 1,
          title: 'Leh acclimatization',
          desc: "Don't move fast. Drink water. Walk the bazaar. Sleep early.",
        },
        {
          day: 2,
          title: 'Over Khardung La',
          desc: 'Long drive over the pass. Stop at the prayer flags. Arrive in Nubra by evening.',
        },
        {
          day: 3,
          title: 'Into Turtuk',
          desc: 'Final 2hr drive along the Shyok. Settle into the homestay. First apricot.',
        },
        {
          day: 4,
          title: 'Wander',
          desc: "Walk the irrigation channels. Eat lunch in someone's orchard. Visit the tiny museum.",
        },
        {
          day: 5,
          title: 'Departure',
          desc: 'Drive back over the pass. Sleep in Leh. Fly out the next morning.',
        },
      ],
    },
  },
  {
    id: 'andasibe',
    name: 'Andasibe',
    country: 'Madagascar',
    region: 'Alaotra-Mangoro, eastern rainforest',
    coords: '18.9°S, 48.4°E',
    voiceNote:
      "The lemurs sing at dawn. Once you've heard it you will never confuse it with anything else.",
    voiceDuration: '0:18',
    prompts: [
      'Can you walk in mud for two days and still smile?',
      'Are you OK with 4am wake-ups for animals?',
    ],
    foodSpots: [
      {
        id: 'andasibe-1',
        name: 'Park entrance kitchen',
        desc: 'A simple lodge kitchen near the park gate serving Malagasy plates between guided walks.',
        funFact:
          "Madagascar's vanilla economy supplies 80% of the world's natural vanilla — and most of it grows within 200km of here.",
        submittedBy: '@rainforest_log',
        map: 'Andasibe village, by the park entrance',
        type: 'Lodge kitchen',
        priceLevel: 2,
        menu: [
          { name: 'Romazava', desc: 'Beef stew with brèdes mafana greens', price: '28,000 MGA' },
          {
            name: 'Henakisoa sy ravitoto',
            desc: 'Pork with shredded cassava leaves',
            price: '32,000 MGA',
          },
          { name: "Vary amin'anana", desc: 'Rice cooked with leafy greens', price: '18,000 MGA' },
          { name: 'Vanilla rum', desc: 'House-infused, 50ml', price: '15,000 MGA' },
        ],
      },
      {
        id: 'andasibe-2',
        name: 'Vanilla farm tasting',
        desc: 'On-farm tasting at a vanilla cooperative. You can pay to roll your own vanilla bean and take it home.',
        funFact: 'Each vanilla flower must be hand-pollinated within 12 hours of opening.',
        submittedBy: '@bean_routes',
        map: '10km north on the RN2, signposted',
        type: 'Farm visit',
        priceLevel: 2,
        menu: [
          {
            name: 'Vanilla tasting flight',
            desc: 'Five varieties, on biscuits',
            price: '30,000 MGA',
          },
          { name: 'Bean roll-your-own', desc: '1 bean to take home', price: '55,000 MGA' },
          { name: 'Vanilla coffee', desc: 'Ground beans + house roast', price: '12,000 MGA' },
        ],
      },
      {
        id: 'andasibe-3',
        name: 'Night-walk café',
        desc: 'Open-late café where guides and travelers gather between night walks looking for chameleons.',
        funFact: "Madagascar has half the world's chameleon species, most found nowhere else.",
        submittedBy: '@nocturnal_trails',
        map: 'Andasibe village center, open till midnight',
        type: 'Café',
        priceLevel: 1,
        menu: [
          { name: 'Mofo gasy', desc: 'Sweet rice-flour pancakes', price: '8,000 MGA' },
          { name: 'THB beer', desc: 'Local lager, large bottle', price: '12,000 MGA' },
          { name: 'Brochettes (3)', desc: 'Grilled zebu skewers', price: '20,000 MGA' },
        ],
      },
      {
        id: 'andasibe-4',
        name: 'Mantadia trail snack stop',
        desc: 'A clearing halfway through the longer Mantadia hike where guides set out fruit and bread for groups.',
        funFact: 'The trail passes through three distinct micro-climates over 8km of elevation.',
        submittedBy: '@guides_chat',
        map: 'Mantadia, km 4 of the long loop',
        type: 'Trail stop',
        priceLevel: 1,
        menu: [
          { name: 'Fruit plate', desc: 'Lychee, papaya, banana — seasonal', price: '10,000 MGA' },
          { name: 'Bread + peanut spread', desc: 'Trail snack', price: '8,000 MGA' },
        ],
      },
    ],
    friction: {
      transport: '3.5hr drive from Antananarivo on a fair road',
      language: 'Malagasy, French in tourist areas',
      connectivity: 'Spotty 3G in village',
    },
    frictionLevel: 60,
    trivia: "90% of Madagascar's wildlife exists nowhere else on Earth.",
    deniedCount: 1,
    visaProb: { IN: 75, NO: 90, NG: 60, PK: 50, US: 90, SY: 35, GB: 92, DE: 92, JP: 90, AU: 85 },
    bestMonths: 'Apr–Oct',
    avgTemp: '20°C',
    currency: 'Malagasy Ariary (MGA)',
    flightHub: 'Antananarivo (TNR)',
    travelPlan: {
      flights: {
        from: 'DEL',
        to: 'TNR',
        airline: 'Kenya Airways via Nairobi',
        duration: '13h 15m',
        stops: 1,
        price: '₹54,000',
      },
      hotels: [
        {
          name: 'Mantadia Lodge',
          type: 'Eco-lodge',
          price: '₹4,800/night',
          desc: 'Wooden bungalows on the forest edge; bird calls wake you instead of an alarm.',
        },
        {
          name: 'Vakôna Forest Lodge',
          type: 'Mid-range hotel',
          price: '₹3,200/night',
          desc: 'Riverside cabins; private lemur reserve on-site for an extra fee.',
        },
      ],
      itinerary: [
        {
          day: 1,
          title: 'Tana → Andasibe',
          desc: 'Drive east. Stop at the chameleon farm. Arrive by sunset; first night walk.',
        },
        {
          day: 2,
          title: 'Indri morning',
          desc: "5am wake-up. Walk into the park. The indri's song will rearrange you.",
        },
        {
          day: 3,
          title: 'Mantadia full day',
          desc: "Long hike in the deeper park. Six lemur species possible if you're patient.",
        },
        {
          day: 4,
          title: 'Vanilla & rest',
          desc: 'Slow morning. Visit the vanilla farm. Last night walk.',
        },
        {
          day: 5,
          title: 'Departure',
          desc: 'Drive back to Tana. International flight late evening.',
        },
      ],
    },
  },
  {
    id: 'bukhara',
    name: 'Bukhara',
    country: 'Uzbekistan',
    region: 'Bukhara Region, Silk Road',
    coords: '39.8°N, 64.4°E',
    voiceNote: "Marco Polo passed through here. The market hasn't changed enough to disagree.",
    voiceDuration: '0:14',
    prompts: [
      "Will you bargain when you don't know the language?",
      'Are you OK eating where the menu has no English?',
    ],
    foodSpots: [
      {
        id: 'bukhara-1',
        name: 'Lyabi Hauz pilov house',
        desc: "Open-air restaurant by the central pool, serving the city's signature pilov in the late afternoon when locals eat their main meal.",
        funFact:
          "Each Uzbek city has its own pilov style — Bukhara's uses raisins and chickpeas, distinguishing it from Tashkent's heavier version.",
        submittedBy: '@silk_table',
        map: 'Lyabi Hauz pool, eastern side',
        type: 'Open-air restaurant',
        priceLevel: 2,
        menu: [
          { name: 'Bukharan pilov', desc: 'Lamb, raisins, carrot, chickpea', price: '55,000 UZS' },
          { name: 'Plov fergana style', desc: 'Heavier, beef-based', price: '60,000 UZS' },
          { name: 'Achichuk salad', desc: 'Tomato, onion, basil', price: '20,000 UZS' },
          { name: 'Black tea pot', desc: 'With dried apricots', price: '10,000 UZS' },
        ],
      },
      {
        id: 'bukhara-2',
        name: 'Madrasah courtyard café',
        desc: 'A small café inside the courtyard of a 16th-century madrasah, now half-restored. Tables sit between lecture cells.',
        funFact:
          'Bukhara had over 200 madrasahs at its peak in the 1500s — the highest concentration in the Islamic world.',
        submittedBy: '@stone_walls',
        map: 'Mir-i-Arab madrasah, side courtyard',
        type: 'Courtyard café',
        priceLevel: 2,
        menu: [
          { name: 'Manti (5 pcs)', desc: 'Hand-rolled lamb dumplings', price: '45,000 UZS' },
          { name: 'Lagman', desc: 'Hand-pulled noodles in broth', price: '40,000 UZS' },
          { name: 'Halva platter', desc: 'Three types, with pomegranate', price: '30,000 UZS' },
        ],
      },
      {
        id: 'bukhara-3',
        name: 'Trading dome bread oven',
        desc: 'Bread oven inside one of the surviving Silk Road trading domes. The non bread sells out by mid-morning.',
        funFact:
          'Bukharan non is so iconic that families took loaves on long voyages — bread that never goes stale.',
        submittedBy: '@bread_caravan',
        map: 'Toki Sarrofon trading dome',
        type: 'Bread oven',
        priceLevel: 1,
        menu: [
          { name: 'Patir non', desc: 'Sesame-topped flatbread', price: '8,000 UZS' },
          { name: 'Plain non', desc: 'Simple, wheel-stamped', price: '5,000 UZS' },
          {
            name: 'Halim',
            desc: 'Wheat-meat porridge, traditional breakfast',
            price: '20,000 UZS',
          },
        ],
      },
      {
        id: 'bukhara-4',
        name: 'Caravanserai shashlik',
        desc: "Restored caravanserai on the city's edge, now serving shashlik to the staff and curious travelers in the courtyard.",
        funFact:
          "Travelers slept here for free for 3 nights; on the 4th night, you paid or the host's hospitality became suspicious.",
        submittedBy: '@road_dust',
        map: 'East caravanserai, 15 min walk from Lyabi Hauz',
        type: 'Courtyard grill',
        priceLevel: 2,
        menu: [
          { name: 'Lamb shashlik (2)', desc: 'Skewered, charcoal-grilled', price: '55,000 UZS' },
          { name: 'Liver shashlik', desc: 'With onion garnish', price: '45,000 UZS' },
          { name: 'Samsa (lamb)', desc: 'Tandoor-baked pastry', price: '18,000 UZS' },
        ],
      },
    ],
    friction: {
      transport: 'Direct flight from Tashkent (1hr) or fast train (4hr)',
      language: 'Uzbek/Russian, some English in tourist areas',
      connectivity: 'Reliable 4G in old city',
    },
    frictionLevel: 35,
    trivia:
      'There are more architectural monuments per square kilometer here than in any other city in Central Asia.',
    deniedCount: 0,
    visaProb: { IN: 92, NO: 99, NG: 70, PK: 78, US: 95, SY: 50, GB: 95, DE: 95, JP: 99, AU: 90 },
    bestMonths: 'Apr–Jun, Sep–Oct',
    avgTemp: '26°C',
    currency: 'Uzbek Som (UZS)',
    flightHub: 'Bukhara (BHK)',
    travelPlan: {
      flights: {
        from: 'DEL',
        to: 'BHK',
        airline: 'Uzbekistan Airways via Tashkent',
        duration: '6h 30m',
        stops: 1,
        price: '₹28,000',
      },
      hotels: [
        {
          name: 'Komil Boutique Hotel',
          type: 'Madrasah conversion',
          price: '₹3,400/night',
          desc: "Family-run, 19th-century merchant's house with a small inner courtyard.",
        },
        {
          name: 'Bibi Khanym Hotel',
          type: 'Mid-range',
          price: '₹2,200/night',
          desc: 'Inside the old city walls; rooms basic but the location is unbeatable.',
        },
      ],
      itinerary: [
        {
          day: 1,
          title: 'Arrive & wander',
          desc: 'Settle in; walk Lyabi Hauz at dusk; eat pilov for dinner.',
        },
        {
          day: 2,
          title: 'Old city core',
          desc: 'Ark Fortress, Bolo Hauz mosque, Kalyan minaret. Long lunch in a courtyard café.',
        },
        {
          day: 3,
          title: 'Trading domes',
          desc: 'Walk all four restored domes. Buy a knife from the bladesmiths if you can fit it in your bag.',
        },
        {
          day: 4,
          title: 'Sitorai Mokhi-Khosa',
          desc: 'Day trip to the summer palace 5km out. Garden tea on return.',
        },
        {
          day: 5,
          title: 'Departure',
          desc: 'Morning train to Samarkand or flight back via Tashkent.',
        },
      ],
    },
  },
  {
    id: 'elchalten',
    name: 'El Chaltén',
    country: 'Argentina',
    region: 'Santa Cruz, Patagonia',
    coords: '49.3°S, 73.0°W',
    voiceNote: 'The mountain is only visible 60 days a year. Today is one of them.',
    voiceDuration: '0:13',
    prompts: [
      'Can you hike 25km in unpredictable weather?',
      'Do you have warm enough socks for 4am summit starts?',
    ],
    foodSpots: [
      {
        id: 'elchalten-1',
        name: 'La Tapera',
        desc: 'Wood-cabin restaurant serving Patagonian lamb and trout to climbers and trekkers. Reservations only on weekends.',
        funFact:
          'Patagonian lamb here is salt-marsh raised — the meat is naturally seasoned by the grass.',
        submittedBy: '@granite_logs',
        map: 'Avenida Antonio Rojo, west end',
        type: "Climber's restaurant",
        priceLevel: 3,
        menu: [
          { name: 'Cordero al asador', desc: 'Slow-roasted lamb, half plate', price: '18,000 ARS' },
          {
            name: 'Trout in butter',
            desc: 'From local lake, lemon-caper sauce',
            price: '14,000 ARS',
          },
          {
            name: 'Calafate berry crumble',
            desc: 'Local dessert; legend says it brings you back',
            price: '5,500 ARS',
          },
          { name: 'Malbec glass', desc: 'From Mendoza, well chosen', price: '3,500 ARS' },
        ],
      },
      {
        id: 'elchalten-2',
        name: "Trekkers' bakery",
        desc: 'A bakery that opens at 5am for climbers heading out. Empanadas to go, hot coffee, sandwich lunches packed in foil.',
        funFact:
          'The owner used to be a Fitz Roy guide — she retired after 30 summits and opened the bakery instead.',
        submittedBy: '@predawn_starts',
        map: 'Main street, opposite the church',
        type: 'Bakery',
        priceLevel: 1,
        menu: [
          { name: 'Empanada (lamb)', desc: 'Hand-pleated, baked', price: '1,800 ARS' },
          {
            name: 'Trail sandwich',
            desc: 'Salami + cheese + bread, foil-wrapped',
            price: '3,500 ARS',
          },
          { name: 'Coffee in a thermos', desc: 'Bring your own, refilled', price: '1,500 ARS' },
        ],
      },
      {
        id: 'elchalten-3',
        name: 'Cervecería La Vinería',
        desc: "Climbers' bar serving end-of-day beer and shared plates. Conversation is half English, half Spanish, all about the weather.",
        funFact:
          'The local IPA is brewed with hops grown 80km north — possible only because of the long Patagonian daylight.',
        submittedBy: '@end_of_day',
        map: 'Plaza, north side',
        type: "Climbers' bar",
        priceLevel: 2,
        menu: [
          { name: 'Patagonia IPA', desc: 'Pint, draft', price: '4,500 ARS' },
          { name: 'Picada plate', desc: 'Cured meats, hard cheese, olives', price: '12,000 ARS' },
          { name: 'Provoleta', desc: 'Grilled provolone, oregano', price: '7,500 ARS' },
        ],
      },
      {
        id: 'elchalten-4',
        name: 'Laguna de los Tres trail snack',
        desc: 'Halfway-up snack stop on the iconic 25km trail to the Fitz Roy viewpoint. Hot chocolate brewed by the family who lives there.',
        funFact:
          "The trail's last hour climbs 400m of scree — many turn back here. Those who continue see the granite up close.",
        submittedBy: '@final_kilometre',
        map: 'Halfway hut on the Laguna de los Tres trail',
        type: 'Trail hut',
        priceLevel: 1,
        menu: [
          { name: 'Hot chocolate', desc: 'Thick, with cinnamon', price: '3,000 ARS' },
          { name: 'Alfajor', desc: 'Dulce de leche cookie', price: '1,200 ARS' },
          { name: 'Bowl of stew', desc: 'Lamb, potato, kept warm', price: '5,500 ARS' },
        ],
      },
    ],
    friction: {
      transport: '3hr from El Calafate airport on paved road',
      language: 'Spanish, English in town',
      connectivity: 'Good in town, none on trails',
    },
    frictionLevel: 50,
    trivia: 'Argentina built this town in 1985 specifically to settle a border dispute with Chile.',
    deniedCount: 0,
    visaProb: { IN: 70, NO: 99, NG: 55, PK: 45, US: 99, SY: 25, GB: 99, DE: 99, JP: 99, AU: 92 },
    bestMonths: 'Nov–Mar',
    avgTemp: '12°C summer',
    currency: 'Argentine Peso (ARS)',
    flightHub: 'El Calafate (FTE)',
    travelPlan: {
      flights: {
        from: 'DEL',
        to: 'FTE',
        airline: 'LATAM via São Paulo + Buenos Aires',
        duration: '32h',
        stops: 2,
        price: '₹95,000',
      },
      hotels: [
        {
          name: 'Hostería Senderos',
          type: 'Mid-range hotel',
          price: '₹6,800/night',
          desc: 'Modern timber rooms with mountain-view windows; serious breakfast for trail days.',
        },
        {
          name: 'Rancho Grande Hostel',
          type: 'Climber hostel',
          price: '₹2,400/night',
          desc: 'Bunks and shared kitchen; the noticeboard alone is worth the visit.',
        },
      ],
      itinerary: [
        {
          day: 1,
          title: 'Calafate → El Chaltén',
          desc: 'Bus or rental car. Arrive by mid-afternoon. Easy walk to the orientation viewpoint.',
        },
        {
          day: 2,
          title: 'Cerro Torre',
          desc: '20km out-and-back. Less crowded than Fitz Roy, equally spectacular if the wind allows.',
        },
        {
          day: 3,
          title: 'Rest day',
          desc: 'Slow morning. Massage at the local cabin. Eat lamb. Sleep early.',
        },
        {
          day: 4,
          title: 'Laguna de los Tres',
          desc: 'Big day. 25km, 4am start, hopefully clear at the granite.',
        },
        {
          day: 5,
          title: 'Departure',
          desc: 'Drive back to Calafate. Maybe see Perito Moreno on the way.',
        },
      ],
    },
  },
  {
    id: 'punakha',
    name: 'Punakha',
    country: 'Bhutan',
    region: 'Punakha District',
    coords: '27.6°N, 89.9°E',
    voiceNote:
      'The dzong sits at the meeting of two rivers. The country was governed from here for 300 years.',
    voiceDuration: '0:15',
    prompts: [
      'Can you sit through three hours of monastery chanting?',
      "Will you eat chili that's a vegetable, not a seasoning?",
    ],
    foodSpots: [
      {
        id: 'punakha-1',
        name: 'Chimi Lhakhang dining',
        desc: 'Family-run restaurant near the fertility temple. Six-table dining room serving the king of Bhutanese dishes: ema datshi.',
        funFact:
          "Bhutan considers chili a vegetable rather than a spice — they're served in piles, not pinches.",
        submittedBy: '@dzong_walks',
        map: 'Sopsokha village, walk to Chimi Lhakhang',
        type: 'Family restaurant',
        priceLevel: 2,
        menu: [
          { name: 'Ema datshi', desc: 'Chili and yak cheese', price: '180 BTN' },
          { name: 'Kewa datshi', desc: 'Potato and cheese, milder', price: '180 BTN' },
          { name: 'Phaksha paa', desc: 'Pork with red chili & radish', price: '240 BTN' },
          { name: 'Red rice plate', desc: 'Bhutanese highland rice', price: '100 BTN' },
        ],
      },
      {
        id: 'punakha-2',
        name: 'Dzong tea garden',
        desc: 'Garden tea house in the shadow of the dzong. Open afternoons; shaded by jacaranda when in bloom.',
        funFact:
          'The dzong was built in 1637 to defend against Tibetan invasions — it has not been damaged once since.',
        submittedBy: '@temple_count',
        map: 'Punakha Dzong, north garden',
        type: 'Tea garden',
        priceLevel: 1,
        menu: [
          { name: 'Suja', desc: 'Butter tea, salty', price: '60 BTN' },
          { name: 'Ngaja', desc: 'Sweet milk tea', price: '60 BTN' },
          { name: 'Khabzey', desc: 'Crispy fried biscuit', price: '40 BTN' },
        ],
      },
      {
        id: 'punakha-3',
        name: 'Lobesa farmstay dinner',
        desc: "Set evening meal in a working rice farmhouse. Multi-course Bhutanese with everything from the family's own land.",
        funFact:
          "Punakha valley produces the country's only red rice — protected by national designation.",
        submittedBy: '@valley_grain',
        map: 'Lobesa village, ask the homestay host',
        type: 'Farmhouse dinner',
        priceLevel: 3,
        menu: [
          {
            name: '5-course Bhutanese set',
            desc: 'Soup, ema datshi, phaksha, vegetable, red rice, dessert',
            price: '950 BTN',
          },
          { name: 'Ara shot', desc: 'Distilled rice spirit, traditional', price: '120 BTN' },
        ],
      },
      {
        id: 'punakha-4',
        name: 'Suspension bridge stall',
        desc: 'Tea & momo stall at the foot of the longest suspension bridge in Bhutan. Open all day, all-weather.',
        funFact:
          'The bridge is 160m long and sways noticeably mid-span; some pilgrims cross on knees.',
        submittedBy: '@bridge_walk',
        map: 'Punakha suspension bridge, eastern landing',
        type: 'Trail stall',
        priceLevel: 1,
        menu: [
          { name: 'Beef momo (5)', desc: 'Steamed dumplings, with chili sauce', price: '120 BTN' },
          { name: 'Vegetable momo (5)', desc: 'Cabbage and ginger filling', price: '100 BTN' },
          { name: 'Tea + biscuit', desc: 'Standard', price: '50 BTN' },
        ],
      },
    ],
    friction: {
      transport: '3hr drive from Paro over Dochula pass',
      language: 'Dzongkha; English widely spoken with guides',
      connectivity: 'Good 4G in valley, weak in monasteries',
    },
    frictionLevel: 45,
    trivia: 'Bhutan measures Gross National Happiness instead of GDP. They mean it.',
    deniedCount: 0,
    visaProb: { IN: 99, NO: 90, NG: 60, PK: 50, US: 92, SY: 30, GB: 92, DE: 92, JP: 95, AU: 90 },
    bestMonths: 'Mar–May, Sep–Nov',
    avgTemp: '20°C',
    currency: 'Bhutanese Ngultrum (BTN)',
    flightHub: 'Paro (PBH)',
    travelPlan: {
      flights: {
        from: 'DEL',
        to: 'PBH',
        airline: 'Druk Air direct',
        duration: '2h 30m',
        stops: 0,
        price: '₹35,000',
      },
      hotels: [
        {
          name: 'Dhensa Boutique Resort',
          type: 'Luxury lodge',
          price: '₹15,000/night',
          desc: 'Hillside suites with valley views; the only hotel where the dzong is part of the morning light.',
        },
        {
          name: 'Punatsangchu Cottages',
          type: 'Mid-range',
          price: '₹4,500/night',
          desc: 'Simple wooden cottages by the river; basic but honest.',
        },
      ],
      itinerary: [
        {
          day: 1,
          title: 'Paro → Punakha',
          desc: 'Drive over Dochula pass — 108 stupas at the top, snow peaks if clear.',
        },
        {
          day: 2,
          title: 'The dzong',
          desc: 'Half-day at Punakha Dzong with guide. Long lunch by the river.',
        },
        {
          day: 3,
          title: 'Suspension bridge & Chimi Lhakhang',
          desc: 'Walk both sides of the river. Visit the fertility temple.',
        },
        {
          day: 4,
          title: 'Farmstay day',
          desc: "Move to a Lobesa farmhouse. Help with rice work if it's the season.",
        },
        { day: 5, title: 'Departure', desc: 'Drive back to Paro for evening flight.' },
      ],
    },
  },
  {
    id: 'socotra',
    name: 'Socotra',
    country: 'Yemen',
    region: 'Socotra Archipelago, Indian Ocean',
    coords: '12.5°N, 53.9°E',
    voiceNote:
      "The trees here look like nothing else on earth. They've been alone for six million years.",
    voiceDuration: '0:17',
    prompts: [
      'Are you OK with one charter flight a week?',
      'Can you camp under stars no city has touched?',
    ],
    foodSpots: [
      {
        id: 'socotra-1',
        name: 'Hadibo fish grill',
        desc: "Open-air grill in the capital town serving the day's tuna and grouper. The catch comes in around 3pm.",
        funFact: 'Socotra has zero industrial fishing — the boats are still wooden and small.',
        submittedBy: '@island_log',
        map: 'Hadibo waterfront, by the boat dock',
        type: 'Grill',
        priceLevel: 2,
        menu: [
          { name: 'Grilled tuna steak', desc: 'Whole, served on banana leaf', price: '12 USD' },
          { name: 'Grouper plate', desc: 'Smaller, more delicate', price: '10 USD' },
          { name: 'Saltah', desc: 'Yemeni meat stew, on side', price: '6 USD' },
          { name: 'Hot bread', desc: 'Stone-oven, brought to table', price: 'Included' },
        ],
      },
      {
        id: 'socotra-2',
        name: 'Wadi Dirhur camp dinner',
        desc: 'Camp dinner at the canyon pool. Cooked by the guides over open fire, eaten by lantern.',
        funFact: 'The wadi pool you swim in has water older than human civilization.',
        submittedBy: '@canyon_nights',
        map: 'Wadi Dirhur camp, entry near Diksam plateau',
        type: 'Camp',
        priceLevel: 2,
        menu: [
          { name: 'Tribal goat', desc: 'Slow-cooked over coals', price: 'Included with camp' },
          { name: 'Rice & bean', desc: 'Generous portion', price: 'Included' },
          { name: "Dragon's blood tea", desc: 'Local infusion from the trees', price: '3 USD' },
        ],
      },
      {
        id: 'socotra-3',
        name: 'Dragonblood tree picnic',
        desc: 'Mid-day picnic spread set out under the iconic dragon-blood trees. Pre-arranged with your guide.',
        funFact:
          "The dragon-blood tree's red sap was used as paint by Greek and Roman painters; it still trades for $200/kg.",
        submittedBy: '@endemic_flora',
        map: 'Diksam plateau, ask your guide for the spot',
        type: 'Picnic',
        priceLevel: 2,
        menu: [
          { name: 'Cold mezze plate', desc: 'Hummus, olives, dates, flatbread', price: '8 USD' },
          { name: 'Honey & ghee', desc: 'Local, dipped with bread', price: '5 USD' },
          { name: 'Fresh dates', desc: 'Heap, eat with hands', price: '3 USD' },
        ],
      },
      {
        id: 'socotra-4',
        name: 'Detwah lagoon shack',
        desc: 'A lone shack at the white-sand lagoon serving lunch to overnight campers. The owner free-dives for the lobster.',
        funFact:
          "Detwah's lagoon is one of the few places on earth where lobster is more common than fish.",
        submittedBy: '@blue_water',
        map: 'Detwah lagoon, west coast',
        type: 'Beach shack',
        priceLevel: 3,
        menu: [
          { name: 'Grilled lobster', desc: 'Whole, with lemon', price: '20 USD' },
          { name: 'Octopus salad', desc: 'Cold, with onion and chili', price: '12 USD' },
          { name: 'Coconut', desc: 'Whole, opened with machete', price: '2 USD' },
        ],
      },
    ],
    friction: {
      transport: 'Charter flight from Abu Dhabi (3hr), one per week',
      language: 'Arabic / Soqotri, very limited English',
      connectivity: 'No data on island; satellite at camps only',
    },
    frictionLevel: 88,
    trivia: "37% of Socotra's plant species exist nowhere else.",
    deniedCount: 12,
    visaProb: { IN: 25, NO: 35, NG: 18, PK: 22, US: 30, SY: 12, GB: 30, DE: 35, JP: 38, AU: 30 },
    bestMonths: 'Oct–Apr',
    avgTemp: '25°C',
    currency: 'Yemeni Rial (YER) / USD accepted',
    flightHub: 'Socotra (SCT)',
    travelPlan: {
      flights: {
        from: 'DEL',
        to: 'SCT',
        airline: 'Charter via Abu Dhabi',
        duration: '8h 40m',
        stops: 1,
        price: '₹110,000',
      },
      hotels: [
        {
          name: 'Hadibo Beach Hotel',
          type: 'Town hotel',
          price: '₹3,200/night',
          desc: 'Only proper hotel in town; basic rooms with intermittent power.',
        },
        {
          name: 'Wadi camp',
          type: 'Tented camp',
          price: '₹2,400/night',
          desc: 'Set camp inside the canyon for two nights; mattresses on the ground, full meal service.',
        },
      ],
      itinerary: [
        {
          day: 1,
          title: 'Arrive in Hadibo',
          desc: 'Charter lands. Slow afternoon. First fish grill at the waterfront.',
        },
        {
          day: 2,
          title: 'Diksam plateau',
          desc: 'Long drive up to the dragon-blood forest. Picnic. Sunset at the trees.',
        },
        {
          day: 3,
          title: 'Wadi Dirhur camp',
          desc: 'Hike into the canyon. Swim in the freshwater pool. Sleep under the stars.',
        },
        {
          day: 4,
          title: 'Detwah lagoon',
          desc: 'Cross to the west coast. White sand, lagoon swim, lobster dinner.',
        },
        { day: 5, title: 'Departure', desc: 'Drive back to Hadibo. Charter departs late evening.' },
      ],
    },
  },
];
