import type { CountryAccess, Destination, ProfileSlide } from './types';

export const MONO = "'JetBrains Mono', 'SF Mono', 'Fira Code', monospace";

export const c = {
  bg: "#000", fg: "#fff",
  dim: "#bbb",
  faint: "#888",
  ghost: "#2a2a2a",
  sub: "#ddd",
  accent: "#fff",
  danger: "#cc4444",
  warn: "#cc9900",
  surface: "#0a0a0a",
} as const;

// ── Countries ──────────────────────────────────────────────────────────────
// Mobility scores approximate the Henley Passport Index (0–100 normalized).
// visaFree + restricted + impossible ≈ 195 destinations.

function mkCountry(name: string, code: string, score: number, visaFree: number): CountryAccess {
  const total = 195;
  const remaining = total - visaFree;
  const restricted = Math.round(remaining * 0.7);
  const impossible = remaining - restricted;
  return { name, code, visaFree, restricted, impossible, score };
}

const COUNTRY_LIST: CountryAccess[] = [
  mkCountry('Singapore', 'SG', 99, 195),
  mkCountry('Japan', 'JP', 98, 193),
  mkCountry('South Korea', 'KR', 97, 192),
  mkCountry('Germany', 'DE', 97, 191),
  mkCountry('Finland', 'FI', 97, 191),
  mkCountry('Italy', 'IT', 97, 191),
  mkCountry('Spain', 'ES', 97, 191),
  mkCountry('France', 'FR', 96, 190),
  mkCountry('Netherlands', 'NL', 96, 190),
  mkCountry('Sweden', 'SE', 96, 190),
  mkCountry('Norway', 'NO', 96, 189),
  mkCountry('Denmark', 'DK', 96, 189),
  mkCountry('Belgium', 'BE', 96, 189),
  mkCountry('Switzerland', 'CH', 96, 189),
  mkCountry('Ireland', 'IE', 96, 189),
  mkCountry('Austria', 'AT', 96, 189),
  mkCountry('Luxembourg', 'LU', 96, 189),
  mkCountry('Portugal', 'PT', 96, 189),
  mkCountry('Greece', 'GR', 95, 188),
  mkCountry('Czech Republic', 'CZ', 95, 188),
  mkCountry('New Zealand', 'NZ', 95, 188),
  mkCountry('United Kingdom', 'GB', 95, 188),
  mkCountry('Australia', 'AU', 95, 188),
  mkCountry('Malta', 'MT', 95, 188),
  mkCountry('Poland', 'PL', 95, 187),
  mkCountry('Hungary', 'HU', 95, 187),
  mkCountry('Canada', 'CA', 95, 187),
  mkCountry('United States', 'US', 96, 186),
  mkCountry('Estonia', 'EE', 95, 187),
  mkCountry('Lithuania', 'LT', 95, 187),
  mkCountry('Latvia', 'LV', 94, 186),
  mkCountry('Slovakia', 'SK', 94, 186),
  mkCountry('Slovenia', 'SI', 94, 186),
  mkCountry('Iceland', 'IS', 94, 186),
  mkCountry('Liechtenstein', 'LI', 92, 182),
  mkCountry('Cyprus', 'CY', 92, 182),
  mkCountry('Croatia', 'HR', 92, 182),
  mkCountry('Romania', 'RO', 91, 180),
  mkCountry('Bulgaria', 'BG', 91, 179),
  mkCountry('Monaco', 'MC', 91, 179),
  mkCountry('San Marino', 'SM', 90, 178),
  mkCountry('Andorra', 'AD', 86, 170),
  mkCountry('Chile', 'CL', 88, 174),
  mkCountry('UAE', 'AE', 92, 182),
  mkCountry('Argentina', 'AR', 86, 171),
  mkCountry('Brazil', 'BR', 88, 173),
  mkCountry('Mexico', 'MX', 80, 159),
  mkCountry('Israel', 'IL', 87, 172),
  mkCountry('Hong Kong', 'HK', 87, 171),
  mkCountry('Taiwan', 'TW', 75, 145),
  mkCountry('Macao', 'MO', 73, 144),
  mkCountry('Mauritius', 'MU', 75, 148),
  mkCountry('Seychelles', 'SC', 76, 152),
  mkCountry('Malaysia', 'MY', 90, 178),
  mkCountry('Uruguay', 'UY', 78, 154),
  mkCountry('Costa Rica', 'CR', 78, 153),
  mkCountry('Trinidad and Tobago', 'TT', 75, 148),
  mkCountry('Panama', 'PA', 75, 147),
  mkCountry('Ukraine', 'UA', 74, 146),
  mkCountry('Serbia', 'RS', 70, 137),
  mkCountry('North Macedonia', 'MK', 65, 128),
  mkCountry('Bosnia and Herzegovina', 'BA', 62, 122),
  mkCountry('Albania', 'AL', 65, 128),
  mkCountry('Moldova', 'MD', 62, 122),
  mkCountry('Georgia', 'GE', 58, 115),
  mkCountry('Turkey', 'TR', 57, 112),
  mkCountry('South Africa', 'ZA', 55, 108),
  mkCountry('Russia', 'RU', 56, 110),
  mkCountry('China', 'CN', 50, 99),
  mkCountry('Thailand', 'TH', 60, 119),
  mkCountry('Vietnam', 'VN', 28, 56),
  mkCountry('Indonesia', 'ID', 38, 76),
  mkCountry('Philippines', 'PH', 36, 71),
  mkCountry('Kazakhstan', 'KZ', 41, 81),
  mkCountry('Saudi Arabia', 'SA', 47, 92),
  mkCountry('Qatar', 'QA', 56, 110),
  mkCountry('Kuwait', 'KW', 52, 102),
  mkCountry('Bahrain', 'BH', 53, 105),
  mkCountry('Oman', 'OM', 50, 99),
  mkCountry('Jordan', 'JO', 25, 50),
  mkCountry('Lebanon', 'LB', 23, 45),
  mkCountry('Egypt', 'EG', 26, 51),
  mkCountry('Morocco', 'MA', 32, 64),
  mkCountry('Tunisia', 'TN', 33, 65),
  mkCountry('Kenya', 'KE', 36, 72),
  mkCountry('Ghana', 'GH', 33, 65),
  mkCountry('Senegal', 'SN', 34, 67),
  mkCountry('Nigeria', 'NG', 24, 46),
  mkCountry('Ethiopia', 'ET', 23, 45),
  mkCountry('Uganda', 'UG', 33, 65),
  mkCountry('Tanzania', 'TZ', 36, 72),
  mkCountry('Rwanda', 'RW', 33, 66),
  mkCountry('Algeria', 'DZ', 26, 51),
  mkCountry('India', 'IN', 32, 62),
  mkCountry('Sri Lanka', 'LK', 22, 43),
  mkCountry('Bangladesh', 'BD', 21, 42),
  mkCountry('Nepal', 'NP', 21, 42),
  mkCountry('Pakistan', 'PK', 20, 38),
  mkCountry('Iran', 'IR', 22, 44),
  mkCountry('Iraq', 'IQ', 16, 31),
  mkCountry('Yemen', 'YE', 17, 33),
  mkCountry('Syria', 'SY', 15, 29),
  mkCountry('Afghanistan', 'AF', 13, 26),
  mkCountry('Somalia', 'SO', 18, 35),
  mkCountry('North Korea', 'KP', 21, 41),
  mkCountry('Cuba', 'CU', 32, 63),
  mkCountry('Venezuela', 'VE', 65, 128),
  mkCountry('Colombia', 'CO', 65, 128),
  mkCountry('Peru', 'PE', 70, 136),
  mkCountry('Ecuador', 'EC', 50, 99),
  mkCountry('Bolivia', 'BO', 41, 82),
  mkCountry('Paraguay', 'PY', 70, 138),
  mkCountry('Dominican Republic', 'DO', 35, 70),
  mkCountry('Jamaica', 'JM', 45, 89),
  mkCountry('Bahamas', 'BS', 78, 154),
];

// Sort alphabetically and build an indexed map for fast lookup
COUNTRY_LIST.sort((a, b) => a.name.localeCompare(b.name));

export const COUNTRIES_ACCESS: Record<string, CountryAccess> = COUNTRY_LIST.reduce(
  (acc, c) => { acc[c.code] = c; return acc; },
  {} as Record<string, CountryAccess>,
);

export const COUNTRIES_LIST: CountryAccess[] = COUNTRY_LIST;

export const PROFILE_SLIDES: ProfileSlide[] = [
  { key: "cuisine", label: "Culinary curiosity", desc: "How far outside your comfort zone will you eat?", low: "Familiar only", high: "I'll eat anything", icon: "◉" },
  { key: "distance", label: "Travel distance", desc: "How far from the nearest airport are you willing to go?", low: "Under 1 hour", high: "Days if needed", icon: "→" },
  { key: "budget", label: "Daily budget", desc: "What can you spend per day, excluding flights?", low: "< $20/day", high: "$150+/day", icon: "$" },
  { key: "risk", label: "Risk tolerance", desc: "How comfortable are you with unpredictability?", low: "I need a plan", high: "Plans ruin it", icon: "△" },
  { key: "language", label: "Language barrier", desc: "Can you function where nobody speaks your language?", low: "Need English", high: "I'll use my hands", icon: "◊" },
  { key: "solitude", label: "Solitude comfort", desc: "How long can you be alone in a foreign place?", low: "A few hours", high: "Weeks, happily", icon: "○" },
];

// ── Destinations ──────────────────────────────────────────────────────────

export const DESTINATIONS: Destination[] = [
  {
    id: "mestia",
    name: "Mestia",
    country: "Georgia",
    region: "Svaneti, Upper Caucasus",
    coords: "43.0°N, 42.7°E",
    voiceNote: "You hear cowbells before you see the village. The bread here is baked in the ground.",
    voiceDuration: "0:15",
    prompts: ["Can you walk 6 hours uphill and call it a good day?", "Will you drink chacha with a stranger at 10am?"],
    foodSpots: [
      {
        id: "mestia-1",
        name: "Window Kitchen",
        desc: "A small, sign-less spot where a local family bakes khachapuri to order. Look for the steam rising from the third house past the stone tower.",
        funFact: "The owner uses a clay oven that's been in the same family for four generations.",
        submittedBy: "@hiker_olga",
        map: "Third house past the stone tower, left side",
        type: "Street food",
        priceLevel: 1,
        menu: [
          { name: "Imeruli khachapuri", desc: "Cheese-stuffed bread, single layer", price: "8 GEL" },
          { name: "Acharuli khachapuri", desc: "Boat-shaped, egg on top", price: "12 GEL" },
          { name: "Lobiani", desc: "Bean-stuffed flatbread", price: "7 GEL" },
          { name: "Sweet kubdari", desc: "Lamb and herbs in dough", price: "10 GEL" },
        ],
      },
      {
        id: "mestia-2",
        name: "Laila's Kitchen",
        desc: "A homestyle place behind the police station serving Svan kubdari — the regional meat-stuffed bread that's distinct from the rest of Georgia.",
        funFact: "Kubdari was traditionally a long-trek food because it stays edible for three days unrefrigerated.",
        submittedBy: "@bread_atlas",
        map: "Behind the police station, wooden gate",
        type: "Home kitchen",
        priceLevel: 1,
        menu: [
          { name: "Beef kubdari", desc: "Ground beef, blue fenugreek, onion", price: "15 GEL" },
          { name: "Lamb kubdari", desc: "House specialty, slow-cooked filling", price: "18 GEL" },
          { name: "Matsoni soup", desc: "Cold yogurt soup with herbs", price: "9 GEL" },
          { name: "Walnut sauce plate", desc: "Cold appetizer with bread", price: "12 GEL" },
        ],
      },
      {
        id: "mestia-3",
        name: "Tower Cellar Wine Bar",
        desc: "Cellar tasting room beneath a Svan tower. Wine is fermented in qvevri — buried clay vessels — using a method UNESCO has called the world's oldest still in use.",
        funFact: "Some of the qvevri here are over 80 years old. They're never washed, only rinsed.",
        submittedBy: "@wine_passport",
        map: "Below the Svan tower near the museum",
        type: "Wine cellar",
        priceLevel: 2,
        menu: [
          { name: "Saperavi flight", desc: "Three reds, qvevri-aged", price: "25 GEL" },
          { name: "Rkatsiteli amber", desc: "Skin-contact white", price: "30 GEL" },
          { name: "Cheese & sulguni board", desc: "Local pairings", price: "22 GEL" },
          { name: "Chacha shot", desc: "Grape brandy, house-distilled", price: "8 GEL" },
        ],
      },
      {
        id: "mestia-4",
        name: "Café Laila",
        desc: "The closest thing to a town square. Traveler-leaning menu with Georgian classics. Reliable WiFi, which doesn't matter once you sit down.",
        funFact: "Three generations of the same family have run a café on this corner since 1968.",
        submittedBy: "@trail_notes",
        map: "Central square, opposite the post office",
        type: "Café",
        priceLevel: 2,
        menu: [
          { name: "Khinkali (8 pcs)", desc: "Hand-pleated soup dumplings", price: "18 GEL" },
          { name: "Mtsvadi", desc: "Skewered pork over vine charcoal", price: "24 GEL" },
          { name: "Eggplant with walnut", desc: "Cold rolls, classic Georgian", price: "16 GEL" },
          { name: "Tarragon soda", desc: "Bright green, very strong", price: "5 GEL" },
        ],
      },
      {
        id: "mestia-5",
        name: "Honey & Bread Stall",
        desc: "Roadside stall on the way to Ushguli selling raw mountain honey, fresh sulguni cheese, and rye bread baked that morning. The vendor is the beekeeper.",
        funFact: "Svan honey is unusually dark because the bees forage on rhododendron above 2000m.",
        submittedBy: "@slowmile",
        map: "Roadside, 8km past Mestia toward Ushguli",
        type: "Roadside stall",
        priceLevel: 1,
        menu: [
          { name: "Mountain honey jar", desc: "500g, take-away", price: "20 GEL" },
          { name: "Sulguni round", desc: "Smoked, 250g", price: "10 GEL" },
          { name: "Rye loaf", desc: "Whole, daily-baked", price: "5 GEL" },
        ],
      },
      {
        id: "mestia-6",
        name: "Old Tower Tavern",
        desc: "Long-table dinners in a stone room. Fixed nightly menu, no choices, no English on the wall. A handful of seats and a queue of regulars.",
        funFact: "The single long table seats 14. Strangers are seated next to each other on purpose.",
        submittedBy: "@feast_log",
        map: "Below the eastern tower cluster",
        type: "Tavern",
        priceLevel: 2,
        menu: [
          { name: "Set dinner", desc: "5 courses, fixed nightly", price: "55 GEL" },
          { name: "Wine pairing", desc: "Three pours", price: "30 GEL" },
          { name: "Dessert tasting", desc: "Pelamushi & churchkhela", price: "12 GEL" },
        ],
      },
    ],
    friction: { transport: "4hr marshrutka from Zugdidi, unpaved last hour", language: "Georgian/Svan, almost no English", connectivity: "Intermittent 3G" },
    frictionLevel: 72,
    trivia: "The local word for 'stranger' is the same word as 'guest.'",
    deniedCount: 3,
    visaProb: { IN: 87, NO: 99, NG: 72, PK: 65, US: 99, SY: 31 },
    bestMonths: "Jun–Sep",
    avgTemp: "18°C summer",
    currency: "Georgian Lari (GEL)",
    flightHub: "Kutaisi (KUT)",
    travelPlan: {
      flights: { from: "DEL", to: "KUT", airline: "Wizz Air via Istanbul", duration: "9h 40m", stops: 1, price: "₹18,400" },
      hotels: [
        { name: "Svan Guesthouse", type: "Family homestay", price: "₹1,200/night", desc: "Stone house, shared bathroom, dinner included. The family speaks zero English and it doesn't matter." },
        { name: "Hotel Tetnuldi", type: "Budget hotel", price: "₹2,800/night", desc: "The only place with reliable WiFi. You won't need it." },
      ],
      itinerary: [
        { day: 1, title: "Arrive & orient", desc: "Marshrutka from Kutaisi. Arrive dazed. Walk the village. Find the bread window. Sleep early." },
        { day: 2, title: "Ushguli trek", desc: "6-hour hike to Europe's highest continuously inhabited village. Pack water. The views will make you forget your legs." },
        { day: 3, title: "The towers", desc: "Explore Svan defensive towers. Visit the ethnographic museum. Get invited to someone's house for chacha. Say yes." },
        { day: 4, title: "Get lost on purpose", desc: "No plan. Walk a direction. See what's there. This is the day the app goes dark." },
        { day: 5, title: "Departure", desc: "Morning marshrutka back. You'll want to stay. Everyone does." },
      ],
      itineraryVariants: {
        classic: [
          { day: 1, title: "Arrive & orient", desc: "Marshrutka from Kutaisi. Walk the village. Find the bread window. Sleep early." },
          { day: 2, title: "Ushguli trek", desc: "6-hour hike to Europe's highest inhabited village. Pack water." },
          { day: 3, title: "The towers", desc: "Explore Svan towers. Ethnographic museum. Chacha with strangers." },
          { day: 4, title: "Get lost on purpose", desc: "No plan. Walk a direction. The app goes dark today." },
          { day: 5, title: "Departure", desc: "Morning marshrutka back to Kutaisi." },
        ],
        adventure: [
          { day: 1, title: "Arrive & gear up", desc: "Land in Kutaisi. Check trekking gear at Café Laila. Sleep early." },
          { day: 2, title: "Mestia → Chuberi traverse", desc: "Multi-day hut trek begins. 14km, 1100m elevation gain." },
          { day: 3, title: "Glacier day", desc: "Ascend toward Chalaadi glacier. Ice axe optional, weather permitting." },
          { day: 4, title: "Ushguli via the high pass", desc: "Cross Latpari pass on horseback. Sleep in Ushguli." },
          { day: 5, title: "Descend & depart", desc: "Truck down to Mestia, marshrutka to Kutaisi the next morning." },
        ],
        relaxed: [
          { day: 1, title: "Arrive & rest", desc: "Slow morning. Settle into your guesthouse. Eat khachapuri." },
          { day: 2, title: "Village wander", desc: "Walk the village in figure-eights. Find the bread window. Find the wine cellar." },
          { day: 3, title: "Museum day", desc: "Mikhail Khergiani ethnographic museum. Long lunch. Read in the square." },
          { day: 4, title: "Honey road", desc: "Easy walk along the Ushguli road. Stop at the honey stall. Turn around." },
          { day: 5, title: "Departure", desc: "Morning marshrutka. Buy two jars of honey. Don't forget the cheese." },
        ],
      },
    },
  },
  {
    id: "harar",
    name: "Harar",
    country: "Ethiopia",
    region: "Harari Region, Eastern Highlands",
    coords: "9.3°N, 42.1°E",
    voiceNote: "The hyenas come at dusk. The man who feeds them learned from his father, who learned from his.",
    voiceDuration: "0:18",
    prompts: ["Can you drink coffee that takes an hour to prepare?", "Are you comfortable in a city with 362 alleyways and no map?"],
    foodSpots: [
      {
        id: "harar-1",
        name: "Shoa Gate Injera House",
        desc: "Family-run spot near the Shoa Gate serving traditional injera plates. Diners share a single platter; eating with the right hand only is the local custom.",
        funFact: "The teff used in injera is the smallest cereal grain in the world — it takes 150 grains to weigh as much as a single grain of wheat.",
        submittedBy: "@horn_of_africa",
        map: "Near the Shoa Gate, downhill, follow the spice smell",
        type: "Local restaurant",
        priceLevel: 1,
        menu: [
          { name: "Injera firfir", desc: "Torn injera in spiced sauce", price: "60 ETB" },
          { name: "Kitfo", desc: "Raw beef minced with mitmita and butter", price: "180 ETB" },
          { name: "Beyaynetu", desc: "Vegetarian sampler — 7 sides on injera", price: "120 ETB" },
          { name: "Tibs", desc: "Pan-fried beef with onion and rosemary", price: "150 ETB" },
        ],
      },
      {
        id: "harar-2",
        name: "Abdullahi's Coffee Ceremony",
        desc: "A traditional Ethiopian coffee ceremony performed in a private home. Green beans roasted in front of you, brewed in three rounds over roughly two hours.",
        funFact: "Refusing the third round (called 'baraka', meaning blessing) is considered an insult here. Pace yourself.",
        submittedBy: "@slow_brew",
        map: "Inside the old city, ask anyone for Abdullahi",
        type: "Coffee ceremony",
        priceLevel: 1,
        menu: [
          { name: "Full ceremony", desc: "Three rounds, popcorn, incense", price: "100 ETB" },
          { name: "Single bunna", desc: "First round, traditional clay cup", price: "30 ETB" },
          { name: "Sugar service", desc: "Add 2 spoons per cup, local style", price: "Free" },
        ],
      },
      {
        id: "harar-3",
        name: "Night Market Juice Stand",
        desc: "Open-air stall in the main market square serving layered fruit juices in tall glasses. The vendor has been working this corner for two decades.",
        funFact: "The signature 'spris' is layered by density alone — no spoon, no tricks.",
        submittedBy: "@market_lights",
        map: "Main market square after 7pm",
        type: "Street vendor",
        priceLevel: 1,
        menu: [
          { name: "Spris (layered)", desc: "Avocado, mango, papaya, guava", price: "50 ETB" },
          { name: "Avocado-mango", desc: "Two-layer classic", price: "35 ETB" },
          { name: "Pure papaya", desc: "Cold, fresh", price: "25 ETB" },
        ],
      },
      {
        id: "harar-4",
        name: "Hyena Gate Café",
        desc: "Open café near the eastern wall where many travelers gather before the dusk hyena feeding. Simple breakfast and lunch fare, very strong coffee.",
        funFact: "Hyenas have been ritually fed at this gate for over 200 years to keep them from the city's livestock.",
        submittedBy: "@dusk_walks",
        map: "Outside the eastern wall, by the hyena viewing area",
        type: "Café",
        priceLevel: 2,
        menu: [
          { name: "Ful with bread", desc: "Mashed fava beans, boiled egg", price: "70 ETB" },
          { name: "Shiro tegabino", desc: "Spiced chickpea stew, clay pot", price: "90 ETB" },
          { name: "Sambusa (4 pcs)", desc: "Fried lentil pastries", price: "60 ETB" },
          { name: "Macchiato", desc: "Italian-Ethiopian, very dense", price: "25 ETB" },
        ],
      },
      {
        id: "harar-5",
        name: "Adare Rooftop",
        desc: "A small rooftop place inside the old city walls. Distant view of the minarets at sunset. Menu is short and changes weekly.",
        funFact: "Harar has 99 mosques inside the walls — one of the highest densities of religious buildings in the world.",
        submittedBy: "@minaret_count",
        map: "Old city, near the Jami mosque, climb three flights",
        type: "Rooftop kitchen",
        priceLevel: 2,
        menu: [
          { name: "Lamb tibs platter", desc: "With injera and ayib", price: "200 ETB" },
          { name: "Vegetable shiro", desc: "Vegan, served bubbling", price: "110 ETB" },
          { name: "Tej", desc: "Honey wine, served in berele flask", price: "80 ETB" },
        ],
      },
      {
        id: "harar-6",
        name: "Spice Market Lunch",
        desc: "Lunch counter inside the spice market — eat sitting on a low bench between sacks of cardamom and chili. The cook has been there since the 1980s.",
        funFact: "The blend you'll smell in the air is berbere — at least 16 spices, never the same twice.",
        submittedBy: "@spice_route",
        map: "Inside the central spice market",
        type: "Market lunch",
        priceLevel: 1,
        menu: [
          { name: "Misir wat", desc: "Red lentil stew, very spicy", price: "75 ETB" },
          { name: "Atkilt wat", desc: "Cabbage, carrot, potato", price: "65 ETB" },
          { name: "Berbere take-home", desc: "100g, hand-blended", price: "120 ETB" },
        ],
      },
    ],
    friction: { transport: "1hr flight from Addis or 8hr bus through the Rift Valley", language: "Harari/Amharic, minimal English", connectivity: "Decent 4G in center, nothing outside" },
    frictionLevel: 68,
    trivia: "This city has been trading coffee for 600 years. Starbucks has existed for 54.",
    deniedCount: 7,
    visaProb: { IN: 91, NO: 97, NG: 78, PK: 70, US: 97, SY: 25 },
    bestMonths: "Oct–Feb",
    avgTemp: "24°C",
    currency: "Ethiopian Birr (ETB)",
    flightHub: "Dire Dawa (DIR)",
    travelPlan: {
      flights: { from: "DEL", to: "DIR", airline: "Ethiopian Airlines via Addis", duration: "8h 20m", stops: 1, price: "₹24,600" },
      hotels: [
        { name: "Ras Hotel Harar", type: "Heritage hotel", price: "₹1,600/night", desc: "Colonial era building in the old city. Creaky floors and the best rooftop view of the minarets." },
        { name: "Rewda homestay", type: "Family home", price: "₹800/night", desc: "Sleeping on traditional mats. Morning coffee ceremony included. The grandmother will adopt you." },
      ],
      itinerary: [
        { day: 1, title: "Enter the walls", desc: "Arrive from Dire Dawa. Walk through the Shoa Gate. Get lost immediately. That's correct." },
        { day: 2, title: "The 362 alleyways", desc: "Wander the old city. Visit the Harari museum. Buy spices you can't name. Eat injera until you can't." },
        { day: 3, title: "Hyena feeding", desc: "At dusk, go to the eastern wall. The Hyena Man will hand you raw meat on a stick. You hold it in your teeth. A hyena takes it from your mouth. This is real." },
        { day: 4, title: "Coffee and nothing else", desc: "Spend the entire day doing coffee ceremonies. Three rounds each. At least two houses. Talk to everyone." },
        { day: 5, title: "Departure", desc: "Bus to Dire Dawa at dawn. The city gets smaller in your window. You'll think about the hyenas for years." },
      ],
      itineraryVariants: {
        classic: [
          { day: 1, title: "Enter the walls", desc: "Arrive from Dire Dawa. Walk through the Shoa Gate." },
          { day: 2, title: "The 362 alleyways", desc: "Old city, Harari museum, spice market." },
          { day: 3, title: "Hyena feeding", desc: "Eastern wall at dusk. The Hyena Man." },
          { day: 4, title: "Coffee day", desc: "Two ceremonies. Three rounds each." },
          { day: 5, title: "Departure", desc: "Bus to Dire Dawa at dawn." },
        ],
        adventure: [
          { day: 1, title: "Land & ride", desc: "Fly to Dire Dawa. Hire a driver into the Chercher highlands." },
          { day: 2, title: "Babile camel market", desc: "Sunday-only camel auction 30km out of town." },
          { day: 3, title: "Hyena overnight", desc: "Walk the wall at dusk. Sleep with the gates open." },
          { day: 4, title: "Old city by horse", desc: "Hire a guide on horseback through the surrounding villages." },
          { day: 5, title: "Departure", desc: "Long bus through the Rift Valley back to Addis." },
        ],
        relaxed: [
          { day: 1, title: "Slow arrival", desc: "Fly to Dire Dawa. Drive in. Long lunch in the old city." },
          { day: 2, title: "Coffee morning", desc: "One ceremony, three rounds. Read on the rooftop after." },
          { day: 3, title: "Wall walk", desc: "Slow loop of the city walls. Hyenas at sunset only if you feel like it." },
          { day: 4, title: "Spice market", desc: "Buy berbere, mitmita. Eat lunch among the sacks." },
          { day: 5, title: "Departure", desc: "Late drive to Dire Dawa. Afternoon flight." },
        ],
      },
    },
  },
  {
    id: "karakol",
    name: "Karakol",
    country: "Kyrgyzstan",
    region: "Issyk-Kul Province, Tian Shan",
    coords: "42.5°N, 78.4°E",
    voiceNote: "The mountains here don't care about you. That's why they're beautiful.",
    voiceDuration: "0:12",
    prompts: ["Can you eat horse meat and not make it weird?", "Do you know how to be cold and happy at the same time?"],
    foodSpots: [
      {
        id: "karakol-1",
        name: "Dungan Ashlan-Fu House",
        desc: "Cold noodles in vinegar broth — a Dungan specialty brought to Kyrgyzstan in the 19th century. The cook follows a recipe that hasn't changed in three decades.",
        funFact: "The Dungan people are descendants of Hui Muslims who fled imperial China in 1877.",
        submittedBy: "@noodle_atlas",
        map: "Behind the central bazaar, blue metal door",
        type: "Home restaurant",
        priceLevel: 1,
        menu: [
          { name: "Ashlan-fu (single)", desc: "Cold noodles, vinegar broth, peas", price: "60 KGS" },
          { name: "Ashlan-fu (double)", desc: "Two bowls, hand-pulled extra", price: "100 KGS" },
          { name: "Pirozhki side", desc: "Fried potato bun, traditional pair", price: "20 KGS" },
        ],
      },
      {
        id: "karakol-2",
        name: "Bazaar Samsa Stand",
        desc: "Tandoor-baked lamb pastries from a single stall at the south entrance of the central bazaar. They sell out by 11am on most days.",
        funFact: "The clay tandoor here is half buried in the ground — locals say the deeper the oven, the better the seal.",
        submittedBy: "@morning_walks",
        map: "Central bazaar, south entrance, first stall on right",
        type: "Bazaar stall",
        priceLevel: 1,
        menu: [
          { name: "Lamb samsa", desc: "Onion, fat, tandoor-baked", price: "50 KGS" },
          { name: "Beef samsa", desc: "Slightly leaner", price: "45 KGS" },
          { name: "Pumpkin samsa", desc: "Seasonal, autumn only", price: "40 KGS" },
        ],
      },
      {
        id: "karakol-3",
        name: "Besh Barmak Family House",
        desc: "Five-finger noodles with horse meat — a Kyrgyz centerpiece dish. Eaten with the right hand from a shared platter. Most guesthouses can arrange it on request.",
        funFact: "'Besh barmak' literally means 'five fingers'. Forks are recent and considered slightly silly here.",
        submittedBy: "@steppe_table",
        map: "Ask your guesthouse — most arrange it directly",
        type: "Home cooking",
        priceLevel: 2,
        menu: [
          { name: "Besh barmak set", desc: "Boiled horse, noodles, broth", price: "350 KGS" },
          { name: "Kymyz", desc: "Fermented mare's milk, cold", price: "60 KGS" },
          { name: "Borsok bread", desc: "Fried dough cubes, table snack", price: "30 KGS" },
        ],
      },
      {
        id: "karakol-4",
        name: "Cafe Zarina",
        desc: "Quiet, family-run café two blocks from the bazaar. Russian-Kyrgyz menu, low prices, good for sitting alone with a book and watching snow fall.",
        funFact: "The owner's mother was the head cook on a Soviet expedition train through Central Asia.",
        submittedBy: "@bookbench",
        map: "Two blocks west of the bazaar, behind the Lenin statue",
        type: "Café",
        priceLevel: 2,
        menu: [
          { name: "Lagman", desc: "Hand-pulled noodles, lamb, vegetables", price: "180 KGS" },
          { name: "Manty (5 pcs)", desc: "Steamed dumplings, sour cream", price: "150 KGS" },
          { name: "Plov", desc: "Carrot-rice, raisins, lamb", price: "170 KGS" },
          { name: "Black tea pot", desc: "Bottomless", price: "40 KGS" },
        ],
      },
      {
        id: "karakol-5",
        name: "Yurt Camp Breakfast",
        desc: "Open-air breakfast served at the Tagaytay yurt camp at dawn. Fresh bread, butter, jam, cream, and honey from the neighbor's bees.",
        funFact: "The bread is baked in the same kazan used to boil meat for dinner — flavor crosses over by design.",
        submittedBy: "@yurt_dawn",
        map: "Tagaytay yurt camp, 12km outside Karakol",
        type: "Yurt breakfast",
        priceLevel: 1,
        menu: [
          { name: "Full breakfast", desc: "Bread, kaymak, jam, honey, eggs", price: "200 KGS" },
          { name: "Kaymak only", desc: "Thick mountain cream, with bread", price: "70 KGS" },
          { name: "Mountain honey", desc: "250g jar", price: "180 KGS" },
        ],
      },
      {
        id: "karakol-6",
        name: "Issyk-Kul Smoked Fish",
        desc: "Lakeside shacks selling smoked osman and chebak from the lake. Pulled from the smoker in the afternoon and eaten with bread on a wooden bench.",
        funFact: "Lake Issyk-Kul never freezes despite being 1600m up — locals say the water remembers the sun.",
        submittedBy: "@lake_eats",
        map: "Lakeshore, 30 min from Karakol toward Cholpon-Ata",
        type: "Lakeside shack",
        priceLevel: 1,
        menu: [
          { name: "Smoked osman", desc: "Whole fish, paper-wrapped", price: "200 KGS" },
          { name: "Smoked chebak", desc: "Smaller, two per portion", price: "120 KGS" },
          { name: "Bread + onion", desc: "On the side, fixed price", price: "30 KGS" },
        ],
      },
    ],
    friction: { transport: "7hr shared taxi from Bishkek, mountain passes", language: "Kyrgyz/Russian, very little English", connectivity: "WiFi in town, nothing in valleys" },
    frictionLevel: 65,
    trivia: "More horses than cars. Nobody here thinks that's unusual.",
    deniedCount: 1,
    visaProb: { IN: 94, NO: 99, NG: 80, PK: 75, US: 99, SY: 40 },
    bestMonths: "Jul–Sep",
    avgTemp: "22°C summer",
    currency: "Kyrgyz Som (KGS)",
    flightHub: "Bishkek Manas (FRU)",
    travelPlan: {
      flights: { from: "DEL", to: "FRU", airline: "Air Manas via Almaty", duration: "6h 10m", stops: 1, price: "₹15,200" },
      hotels: [
        { name: "Tagaytay Yurt Camp", type: "Yurt stay", price: "₹900/night", desc: "Felt walls, wood stove, total silence except the river. Breakfast is fresh bread and honey from the neighbor." },
        { name: "Duet Hostel", type: "Budget hostel", price: "₹600/night", desc: "Run by two sisters who will plan your entire trip if you let them. Don't let them. Get lost instead." },
      ],
      itinerary: [
        { day: 1, title: "The long road in", desc: "Shared taxi from Bishkek. You'll stop for roadside kymyz (fermented mare's milk). Drink it." },
        { day: 2, title: "Jyrgalan Valley", desc: "Hike into the valley. No trails marked. Follow the river. Find the hot spring the locals use." },
        { day: 3, title: "Bazaar day", desc: "Central market. Buy felt, eat samsa, watch the animal trading. Nobody's performing for you. This is Tuesday." },
        { day: 4, title: "Horse day", desc: "Rent a horse. Ride toward the mountains. The horse knows where to go better than you do." },
        { day: 5, title: "Departure", desc: "Shared taxi back. Seven hours of mountain passes. You'll sleep through the best views and dream about the ones you saw awake." },
      ],
      itineraryVariants: {
        classic: [
          { day: 1, title: "The long road in", desc: "Shared taxi from Bishkek. Stop for kymyz." },
          { day: 2, title: "Jyrgalan Valley", desc: "Day hike, hot spring, no trails marked." },
          { day: 3, title: "Bazaar day", desc: "Central market, samsa, animal trading." },
          { day: 4, title: "Horse day", desc: "Ride toward the mountains. Don't steer." },
          { day: 5, title: "Departure", desc: "Shared taxi back. Mountain passes." },
        ],
        adventure: [
          { day: 1, title: "Bishkek → Karakol", desc: "Stock up gear in town." },
          { day: 2, title: "Ala-Kul trek day 1", desc: "Trailhead to Sirota Camp. 14km, river crossings." },
          { day: 3, title: "Ala-Kul Lake day", desc: "Climb the pass. Camp at 3500m next to the lake." },
          { day: 4, title: "Altyn Arashan descent", desc: "Down through the canyon. Hot springs at the end." },
          { day: 5, title: "Departure", desc: "Sore. Triumphant. Shared taxi back." },
        ],
        relaxed: [
          { day: 1, title: "Slow arrival", desc: "Late bus from Bishkek. Long dinner in Karakol." },
          { day: 2, title: "Lake day", desc: "Drive to Issyk-Kul shore. Smoked fish lunch. Read." },
          { day: 3, title: "Bazaar morning", desc: "Slow walk through the market. Buy felt." },
          { day: 4, title: "Yurt overnight", desc: "Out to Tagaytay. Sleep early. Wake before the sun." },
          { day: 5, title: "Departure", desc: "Mid-morning return. Light lunch in Bishkek." },
        ],
      },
    },
  },
];
